### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase
  commentId: T:SuperOffice.CRM.Web.Data.Util.ConfigBase
  id: ConfigBase
  parent: SuperOffice.CRM.Web.Data.Util
  children:
  - SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor(System.Xml.Linq.XElement)
  - SuperOffice.CRM.Web.Data.Util.ConfigBase._element
  - SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren(System.Xml.Linq.XElement,SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup)
  - SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace
  langs:
  - csharp
  - vb
  name: ConfigBase
  nameWithType: ConfigBase
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase
  type: Class
  source:
    path: SuperOffice.CRMWeb
    isExternal: true
  assemblies:
  - SuperOffice.CRMWeb
  namespace: SuperOffice.CRM.Web.Data.Util
  syntax:
    content: public abstract class ConfigBase
    content.vb: Public MustInherit Class ConfigBase
  inheritance:
  - System.Object
  derivedClasses:
  - SuperOffice.CRM.Web.Data.Util.ArchiveConfig
  - SuperOffice.CRM.Web.Data.Util.ColumnConfigBase
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase._element
  commentId: F:SuperOffice.CRM.Web.Data.Util.ConfigBase._element
  id: _element
  parent: SuperOffice.CRM.Web.Data.Util.ConfigBase
  langs:
  - csharp
  - vb
  name: _element
  nameWithType: ConfigBase._element
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase._element
  type: Field
  source:
    path: SuperOffice.CRMWeb
    isExternal: true
  assemblies:
  - SuperOffice.CRMWeb
  namespace: SuperOffice.CRM.Web.Data.Util
  syntax:
    content: protected readonly XElement _element
    return:
      type: System.Xml.Linq.XElement
    content.vb: Protected ReadOnly _element As XElement
  modifiers.csharp:
  - protected
  - readonly
  modifiers.vb:
  - Protected
  - ReadOnly
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor(System.Xml.Linq.XElement)
  commentId: M:SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor(System.Xml.Linq.XElement)
  id: '#ctor(System.Xml.Linq.XElement)'
  parent: SuperOffice.CRM.Web.Data.Util.ConfigBase
  langs:
  - csharp
  - vb
  name: ConfigBase(XElement)
  nameWithType: ConfigBase.ConfigBase(XElement)
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.ConfigBase(System.Xml.Linq.XElement)
  type: Constructor
  source:
    path: SuperOffice.CRMWeb
    isExternal: true
  assemblies:
  - SuperOffice.CRMWeb
  namespace: SuperOffice.CRM.Web.Data.Util
  syntax:
    content: protected ConfigBase(XElement element)
    parameters:
    - id: element
      type: System.Xml.Linq.XElement
    content.vb: Protected Sub New(element As XElement)
  overload: SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren(System.Xml.Linq.XElement,SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup)
  commentId: M:SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren(System.Xml.Linq.XElement,SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup)
  id: LoadChildren(System.Xml.Linq.XElement,SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup)
  parent: SuperOffice.CRM.Web.Data.Util.ConfigBase
  langs:
  - csharp
  - vb
  name: LoadChildren(XElement, ColumnConfigGroup)
  nameWithType: ConfigBase.LoadChildren(XElement, ColumnConfigGroup)
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren(System.Xml.Linq.XElement, SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup)
  type: Method
  source:
    path: SuperOffice.CRMWeb
    isExternal: true
  assemblies:
  - SuperOffice.CRMWeb
  namespace: SuperOffice.CRM.Web.Data.Util
  syntax:
    content: protected static IEnumerable<ColumnConfigBase> LoadChildren(XElement element, ColumnConfigGroup parent)
    parameters:
    - id: element
      type: System.Xml.Linq.XElement
    - id: parent
      type: SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup
    return:
      type: System.Collections.Generic.IEnumerable{SuperOffice.CRM.Web.Data.Util.ColumnConfigBase}
    content.vb: Protected Shared Function LoadChildren(element As XElement, parent As ColumnConfigGroup) As IEnumerable(Of ColumnConfigBase)
  overload: SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren*
  modifiers.csharp:
  - protected
  - static
  modifiers.vb:
  - Protected
  - Shared
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace
  commentId: M:SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace
  id: MakeRawXmlStackTrace
  parent: SuperOffice.CRM.Web.Data.Util.ConfigBase
  langs:
  - csharp
  - vb
  name: MakeRawXmlStackTrace()
  nameWithType: ConfigBase.MakeRawXmlStackTrace()
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace()
  type: Method
  source:
    path: SuperOffice.CRMWeb
    isExternal: true
  assemblies:
  - SuperOffice.CRMWeb
  namespace: SuperOffice.CRM.Web.Data.Util
  syntax:
    content: public virtual string MakeRawXmlStackTrace()
    return:
      type: System.String
    content.vb: Public Overridable Function MakeRawXmlStackTrace As String
  overload: SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: SuperOffice.CRM.Web.Data.Util
  commentId: N:SuperOffice.CRM.Web.Data.Util
  isExternal: true
  name: SuperOffice.CRM.Web.Data.Util
  nameWithType: SuperOffice.CRM.Web.Data.Util
  fullName: SuperOffice.CRM.Web.Data.Util
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Xml.Linq.XElement
  isExternal: true
  name: XElement
  nameWithType: XElement
  fullName: System.Xml.Linq.XElement
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor*
  commentId: Overload:SuperOffice.CRM.Web.Data.Util.ConfigBase.#ctor
  isExternal: true
  name: ConfigBase
  nameWithType: ConfigBase.ConfigBase
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.ConfigBase
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren*
  commentId: Overload:SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren
  isExternal: true
  name: LoadChildren
  nameWithType: ConfigBase.LoadChildren
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.LoadChildren
- uid: SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup
  commentId: T:SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup
  parent: SuperOffice.CRM.Web.Data.Util
  isExternal: true
  name: ColumnConfigGroup
  nameWithType: ColumnConfigGroup
  fullName: SuperOffice.CRM.Web.Data.Util.ColumnConfigGroup
- uid: System.Collections.Generic.IEnumerable{SuperOffice.CRM.Web.Data.Util.ColumnConfigBase}
  commentId: T:System.Collections.Generic.IEnumerable{SuperOffice.CRM.Web.Data.Util.ColumnConfigBase}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<ColumnConfigBase>
  nameWithType: IEnumerable<ColumnConfigBase>
  fullName: System.Collections.Generic.IEnumerable<SuperOffice.CRM.Web.Data.Util.ColumnConfigBase>
  nameWithType.vb: IEnumerable(Of ColumnConfigBase)
  fullName.vb: System.Collections.Generic.IEnumerable(Of SuperOffice.CRM.Web.Data.Util.ColumnConfigBase)
  name.vb: IEnumerable(Of ColumnConfigBase)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: SuperOffice.CRM.Web.Data.Util.ColumnConfigBase
    name: ColumnConfigBase
    nameWithType: ColumnConfigBase
    fullName: SuperOffice.CRM.Web.Data.Util.ColumnConfigBase
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: SuperOffice.CRM.Web.Data.Util.ColumnConfigBase
    name: ColumnConfigBase
    nameWithType: ColumnConfigBase
    fullName: SuperOffice.CRM.Web.Data.Util.ColumnConfigBase
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullName.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace*
  commentId: Overload:SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace
  isExternal: true
  name: MakeRawXmlStackTrace
  nameWithType: ConfigBase.MakeRawXmlStackTrace
  fullName: SuperOffice.CRM.Web.Data.Util.ConfigBase.MakeRawXmlStackTrace
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
