### YamlMime:ManagedReference
items:
- uid: SuperOffice.WebApi.Data.Configuration
  commentId: T:SuperOffice.WebApi.Data.Configuration
  id: Configuration
  parent: SuperOffice.WebApi.Data
  children:
  - SuperOffice.WebApi.Data.Configuration.#ctor
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: Configuration
  fullName: SuperOffice.WebApi.Data.Configuration
  type: Class
  source:
    path: SuperOffice.WebApi
    isExternal: true
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  summary: "\nCarrier object for Configuration.\nThis service support fetching of client interface configuration data.\n&lt;para/>\nClient configuration data include Application configuration, which defines how an application is composed out of pages; and page configuration that defines how a page is built out of panels, cards, views and controls.\n&lt;para/>\nSeparate access points also exist for fetching object mappings and filter lists.    \n"
  syntax:
    content: 'public class Configuration : Carrier'
    content.vb: >-
      Public Class Configuration
          Inherits Carrier
  seealso:
  - linkId: SuperOffice.WebApi.Agents.ConfigurationAgent
    commentId: T:SuperOffice.WebApi.Agents.ConfigurationAgent
  inheritance:
  - System.Object
  - SuperOffice.WebApi.Data.Carrier
  inheritedMembers:
  - SuperOffice.WebApi.Data.Carrier.TableRight
  - SuperOffice.WebApi.Data.Carrier.FieldProperties
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.WebApi.Data.Configuration.#ctor
  commentId: M:SuperOffice.WebApi.Data.Configuration.#ctor
  id: '#ctor'
  parent: SuperOffice.WebApi.Data.Configuration
  langs:
  - csharp
  - vb
  name: Configuration()
  nameWithType: Configuration.Configuration()
  fullName: SuperOffice.WebApi.Data.Configuration.Configuration()
  type: Constructor
  source:
    path: SuperOffice.WebApi
    isExternal: true
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  summary: "\nDefault constructor - defaults any enum props to 0. \n"
  syntax:
    content: public Configuration()
    content.vb: Public Sub New
  overload: SuperOffice.WebApi.Data.Configuration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: SuperOffice.WebApi.Data
  commentId: N:SuperOffice.WebApi.Data
  isExternal: true
  name: SuperOffice.WebApi.Data
  nameWithType: SuperOffice.WebApi.Data
  fullName: SuperOffice.WebApi.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.WebApi.Data.Carrier
  commentId: T:SuperOffice.WebApi.Data.Carrier
  parent: SuperOffice.WebApi.Data
  isExternal: true
  name: Carrier
  nameWithType: Carrier
  fullName: SuperOffice.WebApi.Data.Carrier
- uid: SuperOffice.WebApi.Data.Carrier.TableRight
  commentId: P:SuperOffice.WebApi.Data.Carrier.TableRight
  parent: SuperOffice.WebApi.Data.Carrier
  isExternal: true
  name: TableRight
  nameWithType: Carrier.TableRight
  fullName: SuperOffice.WebApi.Data.Carrier.TableRight
- uid: SuperOffice.WebApi.Data.Carrier.FieldProperties
  commentId: P:SuperOffice.WebApi.Data.Carrier.FieldProperties
  parent: SuperOffice.WebApi.Data.Carrier
  isExternal: true
  name: FieldProperties
  nameWithType: Carrier.FieldProperties
  fullName: SuperOffice.WebApi.Data.Carrier.FieldProperties
- uid: SuperOffice.WebApi.Agents.ConfigurationAgent
  commentId: T:SuperOffice.WebApi.Agents.ConfigurationAgent
  isExternal: true
  name: ConfigurationAgent
  nameWithType: ConfigurationAgent
  fullName: SuperOffice.WebApi.Agents.ConfigurationAgent
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.WebApi.Data.Configuration.#ctor*
  commentId: Overload:SuperOffice.WebApi.Data.Configuration.#ctor
  isExternal: true
  name: Configuration
  nameWithType: Configuration.Configuration
  fullName: SuperOffice.WebApi.Data.Configuration.Configuration
