### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration
  commentId: T:SuperOffice.CRM.Services.QuoteLineConfiguration
  id: QuoteLineConfiguration
  parent: SuperOffice.CRM.Services
  children:
  - SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor
  - SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
  - SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
  - SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
  - SuperOffice.CRM.Services.QuoteLineConfiguration.Label
  - SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
  - SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
  - SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
  - SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
  - SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
  - SuperOffice.CRM.Services.QuoteLineConfiguration.ToString
  - SuperOffice.CRM.Services.QuoteLineConfiguration.ToString(System.String)
  langs:
  - csharp
  - vb
  name: QuoteLineConfiguration
  nameWithType: QuoteLineConfiguration
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration
  type: Class
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nQuoteLineConfiguration contains information about which configuration fields that is visible in the GUI. Read only and mandatory fields are also specified.\n<p></p>\nCarrier object for QuoteLineConfiguration.\nServices for the QuoteLineConfiguration Carrier is available from the <xref href=\"SuperOffice.CRM.Services.IQuoteAgent\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: 'public class QuoteLineConfiguration : Carrier'
    content.vb: >-
      Public Class QuoteLineConfiguration
          Inherits Carrier
  seealso:
  - linkId: SuperOffice.CRM.Services.QuoteAgent
    commentId: T:SuperOffice.CRM.Services.QuoteAgent
  - linkId: SuperOffice.CRM.Services.IQuoteAgent
    commentId: T:SuperOffice.CRM.Services.IQuoteAgent
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor
  commentId: M:SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: QuoteLineConfiguration()
  nameWithType: QuoteLineConfiguration.QuoteLineConfiguration()
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfiguration()
  type: Constructor
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nDefault constructor\n"
  syntax:
    content: public QuoteLineConfiguration()
    content.vb: Public Sub New
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString
  commentId: M:SuperOffice.CRM.Services.QuoteLineConfiguration.ToString
  id: ToString
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: QuoteLineConfiguration.ToString()
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString()
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string.\n"
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Overrides Function ToString As String
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString(System.String)
  commentId: M:SuperOffice.CRM.Services.QuoteLineConfiguration.ToString(System.String)
  id: ToString(System.String)
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: ToString(String)
  nameWithType: QuoteLineConfiguration.ToString(String)
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString(System.String)
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string, useful for debugging.\nEach line in the output is prefixed with the input value.\n"
  syntax:
    content: public string ToString(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: The line prefix (typically used for indenting)
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Function ToString(prefix As String) As String
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
  id: QuoteLineConfigurationId
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: QuoteLineConfigurationId
  nameWithType: QuoteLineConfiguration.QuoteLineConfigurationId
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nPrimary key \n"
  syntax:
    content: public virtual int QuoteLineConfigurationId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overridable Property QuoteLineConfigurationId As Integer
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
  id: FieldName
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: FieldName
  nameWithType: QuoteLineConfiguration.FieldName
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe name of the field being configured, from data dictionary \n"
  syntax:
    content: public virtual string FieldName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property FieldName As String
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Label
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.Label
  id: Label
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: Label
  nameWithType: QuoteLineConfiguration.Label
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Label
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nLabel resource string. \n"
  syntax:
    content: public virtual string Label { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property Label As String
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.Label*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
  id: Tooltip
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: Tooltip
  nameWithType: QuoteLineConfiguration.Tooltip
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nTooltip resource string. \n"
  syntax:
    content: public virtual string Tooltip { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property Tooltip As String
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
  id: Editable
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: Editable
  nameWithType: QuoteLineConfiguration.Editable
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nIs this a read only field? \n"
  syntax:
    content: public virtual bool Editable { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable Property Editable As Boolean
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.Editable*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
  id: InUse
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: InUse
  nameWithType: QuoteLineConfiguration.InUse
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nShould this field be displayed in the GUI? \n"
  syntax:
    content: public virtual bool InUse { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable Property InUse As Boolean
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.InUse*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
  id: Mandatory
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: Mandatory
  nameWithType: QuoteLineConfiguration.Mandatory
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nIs this a mandatory field? \n"
  syntax:
    content: public virtual bool Mandatory { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable Property Mandatory As Boolean
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
  id: Rank
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: Rank
  nameWithType: QuoteLineConfiguration.Rank
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nRank of the field \n"
  syntax:
    content: public virtual int Rank { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overridable Property Rank As Integer
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.Rank*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
  commentId: P:SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
  id: RestrictEdit
  parent: SuperOffice.CRM.Services.QuoteLineConfiguration
  langs:
  - csharp
  - vb
  name: RestrictEdit
  nameWithType: QuoteLineConfiguration.RestrictEdit
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nIf true, then this field cannot be set readwrite or mandatory: It&apos;s bound to be readonly \n"
  syntax:
    content: public virtual bool RestrictEdit { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable Property RestrictEdit As Boolean
  overload: SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: SuperOffice.CRM.Services
  commentId: N:SuperOffice.CRM.Services
  isExternal: true
  name: SuperOffice.CRM.Services
  nameWithType: SuperOffice.CRM.Services
  fullName: SuperOffice.CRM.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.CRM.Services.QuoteAgent
  commentId: T:SuperOffice.CRM.Services.QuoteAgent
  isExternal: true
  name: QuoteAgent
  nameWithType: QuoteAgent
  fullName: SuperOffice.CRM.Services.QuoteAgent
- uid: SuperOffice.CRM.Services.IQuoteAgent
  commentId: T:SuperOffice.CRM.Services.IQuoteAgent
  parent: SuperOffice.CRM.Services
  isExternal: true
  name: IQuoteAgent
  nameWithType: IQuoteAgent
  fullName: SuperOffice.CRM.Services.IQuoteAgent
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.#ctor
  isExternal: true
  name: QuoteLineConfiguration
  nameWithType: QuoteLineConfiguration.QuoteLineConfiguration
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfiguration
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.ToString
  isExternal: true
  name: ToString
  nameWithType: QuoteLineConfiguration.ToString
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
  isExternal: true
  name: QuoteLineConfigurationId
  nameWithType: QuoteLineConfiguration.QuoteLineConfigurationId
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.QuoteLineConfigurationId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
  isExternal: true
  name: FieldName
  nameWithType: QuoteLineConfiguration.FieldName
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.FieldName
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Label*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.Label
  isExternal: true
  name: Label
  nameWithType: QuoteLineConfiguration.Label
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Label
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
  isExternal: true
  name: Tooltip
  nameWithType: QuoteLineConfiguration.Tooltip
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Tooltip
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Editable*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
  isExternal: true
  name: Editable
  nameWithType: QuoteLineConfiguration.Editable
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Editable
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.InUse*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
  isExternal: true
  name: InUse
  nameWithType: QuoteLineConfiguration.InUse
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.InUse
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
  isExternal: true
  name: Mandatory
  nameWithType: QuoteLineConfiguration.Mandatory
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Mandatory
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.Rank*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
  isExternal: true
  name: Rank
  nameWithType: QuoteLineConfiguration.Rank
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.Rank
- uid: SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit*
  commentId: Overload:SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
  isExternal: true
  name: RestrictEdit
  nameWithType: QuoteLineConfiguration.RestrictEdit
  fullName: SuperOffice.CRM.Services.QuoteLineConfiguration.RestrictEdit
