### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Services.AudienceConfigParameter
  commentId: T:SuperOffice.CRM.Services.AudienceConfigParameter
  id: AudienceConfigParameter
  parent: SuperOffice.CRM.Services
  children:
  - SuperOffice.CRM.Services.AudienceConfigParameter.#ctor
  - SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
  - SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
  - SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
  - SuperOffice.CRM.Services.AudienceConfigParameter.Name
  - SuperOffice.CRM.Services.AudienceConfigParameter.ToString
  - SuperOffice.CRM.Services.AudienceConfigParameter.ToString(System.String)
  - SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
  - SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
  - SuperOffice.CRM.Services.AudienceConfigParameter.Value
  langs:
  - csharp
  - vb
  name: AudienceConfigParameter
  nameWithType: AudienceConfigParameter
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter
  type: Class
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nAn Audience configuration parameter, used for handling Audience application or Web part settings.\n<p></p>\nCarrier object for AudienceConfigParameter.\nServices for the AudienceConfigParameter Carrier is available from the <xref href=\"SuperOffice.CRM.Services.IAudienceAgent\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: 'public class AudienceConfigParameter : Carrier'
    content.vb: >-
      Public Class AudienceConfigParameter
          Inherits Carrier
  seealso:
  - linkId: SuperOffice.CRM.Services.AudienceAgent
    commentId: T:SuperOffice.CRM.Services.AudienceAgent
  - linkId: SuperOffice.CRM.Services.IAudienceAgent
    commentId: T:SuperOffice.CRM.Services.IAudienceAgent
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.#ctor
  commentId: M:SuperOffice.CRM.Services.AudienceConfigParameter.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: AudienceConfigParameter()
  nameWithType: AudienceConfigParameter.AudienceConfigParameter()
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceConfigParameter()
  type: Constructor
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nDefault constructor\n"
  syntax:
    content: public AudienceConfigParameter()
    content.vb: Public Sub New
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.ToString
  commentId: M:SuperOffice.CRM.Services.AudienceConfigParameter.ToString
  id: ToString
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: AudienceConfigParameter.ToString()
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.ToString()
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string.\n"
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Overrides Function ToString As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.ToString(System.String)
  commentId: M:SuperOffice.CRM.Services.AudienceConfigParameter.ToString(System.String)
  id: ToString(System.String)
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: ToString(String)
  nameWithType: AudienceConfigParameter.ToString(String)
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.ToString(System.String)
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string, useful for debugging.\nEach line in the output is prefixed with the input value.\n"
  syntax:
    content: public string ToString(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: The line prefix (typically used for indenting)
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Function ToString(prefix As String) As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.ToString*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
  id: AudienceLayoutId
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: AudienceLayoutId
  nameWithType: AudienceConfigParameter.AudienceLayoutId
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe id of the Audience layout this configuration setting belongs to \n"
  syntax:
    content: public virtual int AudienceLayoutId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overridable Property AudienceLayoutId As Integer
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.Name
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.Name
  id: Name
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: AudienceConfigParameter.Name
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.Name
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe name of the configuration parameter \n"
  syntax:
    content: public virtual string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property Name As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.Name*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.Value
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.Value
  id: Value
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: AudienceConfigParameter.Value
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.Value
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe value of the configuration parameter \n"
  syntax:
    content: public virtual string Value { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property Value As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.Value*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
  id: CreatedDate
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: CreatedDate
  nameWithType: AudienceConfigParameter.CreatedDate
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe date and time the configuration parameter was created  in UTC.\n"
  syntax:
    content: public virtual DateTime CreatedDate { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Overridable Property CreatedDate As Date
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
  id: UpdatedDate
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: UpdatedDate
  nameWithType: AudienceConfigParameter.UpdatedDate
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe date and time the configuration parameter was last updated  in UTC.\n"
  syntax:
    content: public virtual DateTime UpdatedDate { get; set; }
    parameters: []
    return:
      type: System.DateTime
    content.vb: Public Overridable Property UpdatedDate As Date
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
  id: CreatedBy
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: CreatedBy
  nameWithType: AudienceConfigParameter.CreatedBy
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nName of the person that created the configuration parameter \n"
  syntax:
    content: public virtual string CreatedBy { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property CreatedBy As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
  commentId: P:SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
  id: UpdatedBy
  parent: SuperOffice.CRM.Services.AudienceConfigParameter
  langs:
  - csharp
  - vb
  name: UpdatedBy
  nameWithType: AudienceConfigParameter.UpdatedBy
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nName of the person that last updated the configuration parameter \n"
  syntax:
    content: public virtual string UpdatedBy { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property UpdatedBy As String
  overload: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: SuperOffice.CRM.Services
  commentId: N:SuperOffice.CRM.Services
  isExternal: true
  name: SuperOffice.CRM.Services
  nameWithType: SuperOffice.CRM.Services
  fullName: SuperOffice.CRM.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.CRM.Services.AudienceAgent
  commentId: T:SuperOffice.CRM.Services.AudienceAgent
  isExternal: true
  name: AudienceAgent
  nameWithType: AudienceAgent
  fullName: SuperOffice.CRM.Services.AudienceAgent
- uid: SuperOffice.CRM.Services.IAudienceAgent
  commentId: T:SuperOffice.CRM.Services.IAudienceAgent
  parent: SuperOffice.CRM.Services
  isExternal: true
  name: IAudienceAgent
  nameWithType: IAudienceAgent
  fullName: SuperOffice.CRM.Services.IAudienceAgent
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.#ctor*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.#ctor
  isExternal: true
  name: AudienceConfigParameter
  nameWithType: AudienceConfigParameter.AudienceConfigParameter
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceConfigParameter
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.ToString*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.ToString
  isExternal: true
  name: ToString
  nameWithType: AudienceConfigParameter.ToString
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
  isExternal: true
  name: AudienceLayoutId
  nameWithType: AudienceConfigParameter.AudienceLayoutId
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.AudienceLayoutId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.Name*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.Name
  isExternal: true
  name: Name
  nameWithType: AudienceConfigParameter.Name
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.Name
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.Value*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.Value
  isExternal: true
  name: Value
  nameWithType: AudienceConfigParameter.Value
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.Value
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
  isExternal: true
  name: CreatedDate
  nameWithType: AudienceConfigParameter.CreatedDate
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedDate
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
  isExternal: true
  name: UpdatedDate
  nameWithType: AudienceConfigParameter.UpdatedDate
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedDate
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
  isExternal: true
  name: CreatedBy
  nameWithType: AudienceConfigParameter.CreatedBy
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.CreatedBy
- uid: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy*
  commentId: Overload:SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
  isExternal: true
  name: UpdatedBy
  nameWithType: AudienceConfigParameter.UpdatedBy
  fullName: SuperOffice.CRM.Services.AudienceConfigParameter.UpdatedBy
