### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Services.SmsConfig
  commentId: T:SuperOffice.CRM.Services.SmsConfig
  id: SmsConfig
  parent: SuperOffice.CRM.Services
  children:
  - SuperOffice.CRM.Services.SmsConfig.#ctor
  - SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
  - SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
  - SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
  - SuperOffice.CRM.Services.SmsConfig.NsPluginSender
  - SuperOffice.CRM.Services.SmsConfig.ToString
  - SuperOffice.CRM.Services.SmsConfig.ToString(System.String)
  langs:
  - csharp
  - vb
  name: SmsConfig
  nameWithType: SmsConfig
  fullName: SuperOffice.CRM.Services.SmsConfig
  type: Class
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nSms settings for Customer Service sms providers.\n<p></p>\nCarrier object for SmsConfig.\nServices for the SmsConfig Carrier is available from the <xref href=\"SuperOffice.CRM.Services.ICustomerServiceAgent\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: 'public class SmsConfig : Carrier'
    content.vb: >-
      Public Class SmsConfig
          Inherits Carrier
  seealso:
  - linkId: SuperOffice.CRM.Services.CustomerServiceAgent
    commentId: T:SuperOffice.CRM.Services.CustomerServiceAgent
  - linkId: SuperOffice.CRM.Services.ICustomerServiceAgent
    commentId: T:SuperOffice.CRM.Services.ICustomerServiceAgent
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.CRM.Services.SmsConfig.#ctor
  commentId: M:SuperOffice.CRM.Services.SmsConfig.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: SmsConfig()
  nameWithType: SmsConfig.SmsConfig()
  fullName: SuperOffice.CRM.Services.SmsConfig.SmsConfig()
  type: Constructor
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nDefault constructor\n"
  syntax:
    content: public SmsConfig()
    content.vb: Public Sub New
  overload: SuperOffice.CRM.Services.SmsConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.SmsConfig.ToString
  commentId: M:SuperOffice.CRM.Services.SmsConfig.ToString
  id: ToString
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: SmsConfig.ToString()
  fullName: SuperOffice.CRM.Services.SmsConfig.ToString()
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string.\n"
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Overrides Function ToString As String
  overload: SuperOffice.CRM.Services.SmsConfig.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: SuperOffice.CRM.Services.SmsConfig.ToString(System.String)
  commentId: M:SuperOffice.CRM.Services.SmsConfig.ToString(System.String)
  id: ToString(System.String)
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: ToString(String)
  nameWithType: SmsConfig.ToString(String)
  fullName: SuperOffice.CRM.Services.SmsConfig.ToString(System.String)
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string, useful for debugging.\nEach line in the output is prefixed with the input value.\n"
  syntax:
    content: public string ToString(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: The line prefix (typically used for indenting)
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Function ToString(prefix As String) As String
  overload: SuperOffice.CRM.Services.SmsConfig.ToString*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
  commentId: P:SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
  id: DefaultSmsCountry
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: DefaultSmsCountry
  nameWithType: SmsConfig.DefaultSmsCountry
  fullName: SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nPhone prefix, will default to the current users HomeCountryId. \n"
  syntax:
    content: public virtual string DefaultSmsCountry { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property DefaultSmsCountry As String
  overload: SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
  commentId: P:SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
  id: NetServerSmsProvider
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: NetServerSmsProvider
  nameWithType: SmsConfig.NetServerSmsProvider
  fullName: SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nName of the selected provider, i.e. CM, Compaya SMS (cpsms.dk), Intelecom SMS, PSWinCom SMS, SMS Teknik or TXTLocal. \n"
  syntax:
    content: public virtual string NetServerSmsProvider { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property NetServerSmsProvider As String
  overload: SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.SmsConfig.NsPluginSender
  commentId: P:SuperOffice.CRM.Services.SmsConfig.NsPluginSender
  id: NsPluginSender
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: NsPluginSender
  nameWithType: SmsConfig.NsPluginSender
  fullName: SuperOffice.CRM.Services.SmsConfig.NsPluginSender
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nThe sender of the SMS messages. This text will appear on the recipient&apos;s mobile phone. \n"
  syntax:
    content: public virtual string NsPluginSender { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property NsPluginSender As String
  overload: SuperOffice.CRM.Services.SmsConfig.NsPluginSender*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
  commentId: P:SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
  id: NsPluginConfig
  parent: SuperOffice.CRM.Services.SmsConfig
  langs:
  - csharp
  - vb
  name: NsPluginConfig
  nameWithType: SmsConfig.NsPluginConfig
  fullName: SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nConfiguration settings provided by the SMS provider. Typically contains newline-delimited settings such as username and password. \n"
  syntax:
    content: public virtual StringDictionary NsPluginConfig { get; set; }
    parameters: []
    return:
      type: SuperOffice.CRM.Services.StringDictionary
    content.vb: Public Overridable Property NsPluginConfig As StringDictionary
  overload: SuperOffice.CRM.Services.SmsConfig.NsPluginConfig*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: SuperOffice.CRM.Services
  commentId: N:SuperOffice.CRM.Services
  isExternal: true
  name: SuperOffice.CRM.Services
  nameWithType: SuperOffice.CRM.Services
  fullName: SuperOffice.CRM.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.CRM.Services.CustomerServiceAgent
  commentId: T:SuperOffice.CRM.Services.CustomerServiceAgent
  isExternal: true
  name: CustomerServiceAgent
  nameWithType: CustomerServiceAgent
  fullName: SuperOffice.CRM.Services.CustomerServiceAgent
- uid: SuperOffice.CRM.Services.ICustomerServiceAgent
  commentId: T:SuperOffice.CRM.Services.ICustomerServiceAgent
  parent: SuperOffice.CRM.Services
  isExternal: true
  name: ICustomerServiceAgent
  nameWithType: ICustomerServiceAgent
  fullName: SuperOffice.CRM.Services.ICustomerServiceAgent
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.CRM.Services.SmsConfig.#ctor*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.#ctor
  isExternal: true
  name: SmsConfig
  nameWithType: SmsConfig.SmsConfig
  fullName: SuperOffice.CRM.Services.SmsConfig.SmsConfig
- uid: SuperOffice.CRM.Services.SmsConfig.ToString*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.ToString
  isExternal: true
  name: ToString
  nameWithType: SmsConfig.ToString
  fullName: SuperOffice.CRM.Services.SmsConfig.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
  isExternal: true
  name: DefaultSmsCountry
  nameWithType: SmsConfig.DefaultSmsCountry
  fullName: SuperOffice.CRM.Services.SmsConfig.DefaultSmsCountry
- uid: SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
  isExternal: true
  name: NetServerSmsProvider
  nameWithType: SmsConfig.NetServerSmsProvider
  fullName: SuperOffice.CRM.Services.SmsConfig.NetServerSmsProvider
- uid: SuperOffice.CRM.Services.SmsConfig.NsPluginSender*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.NsPluginSender
  isExternal: true
  name: NsPluginSender
  nameWithType: SmsConfig.NsPluginSender
  fullName: SuperOffice.CRM.Services.SmsConfig.NsPluginSender
- uid: SuperOffice.CRM.Services.SmsConfig.NsPluginConfig*
  commentId: Overload:SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
  isExternal: true
  name: NsPluginConfig
  nameWithType: SmsConfig.NsPluginConfig
  fullName: SuperOffice.CRM.Services.SmsConfig.NsPluginConfig
- uid: SuperOffice.CRM.Services.StringDictionary
  isExternal: true
  name: StringDictionary
  nameWithType: StringDictionary
  fullName: SuperOffice.CRM.Services.StringDictionary
