### YamlMime:ManagedReference
items:
- uid: CRMScript.NetServer.ConfigType
  children:
  - CRMScript.NetServer.ConfigType.Style
  - CRMScript.NetServer.ConfigType.Options
  langs:
  - crmscript
  type: Enum
  so.intellisense: ConfigType
  syntax: 
    content: ConfigType
  summary: "Value for field 'type' in table 'cust_config'."
  name: ConfigType
  nameWithType: ConfigType
  fullName: CRMScript.NetServer.ConfigType
- uid: CRMScript.NetServer.ConfigType.Style
  langs:
  - crmscript
  type: Field
  so.intellisense: ConfigType.Style
  syntax: 
    content: ConfigType.Style
  summary: "The row contains style data"
  name: Style
  nameWithType: Style
  fullName: CRMScript.NetServer.ConfigType.Style
- uid: CRMScript.NetServer.ConfigType.Options
  langs:
  - crmscript
  type: Field
  so.intellisense: ConfigType.Options
  syntax: 
    content: ConfigType.Options
  summary: "The row contains options data"
  name: Options
  nameWithType: Options
  fullName: CRMScript.NetServer.ConfigType.Options
references:
- uid: CRMScript.NetServer.ConfigType
  commentId: T:CRMScript.NetServer.ConfigType
  isExternal: true
  name: ConfigType
  nameWithType: ConfigType
  fullName: CRMScript.NetServer.ConfigType
