### YamlMime:ManagedReference
items:
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin
  commentId: T:SuperOffice.Events.IGlobalApplicationEventsPlugin
  id: IGlobalApplicationEventsPlugin
  parent: SuperOffice.Events
  children:
  - SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End(System.Web.HttpApplication,System.Object,System.EventArgs)
  - SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error(System.Web.HttpApplication,System.Object,System.EventArgs)
  - SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start(System.Web.HttpApplication,System.Object,System.EventArgs)
  langs:
  - csharp
  - vb
  name: IGlobalApplicationEventsPlugin
  nameWithType: IGlobalApplicationEventsPlugin
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin
  type: Interface
  source:
    path: SOCore
    isExternal: true
  assemblies:
  - SOCore
  namespace: SuperOffice.Events
  summary: "\nImplement interface to handle global application events\n"
  syntax:
    content: 'public interface IGlobalApplicationEventsPlugin : IPlugin'
    content.vb: >-
      Public Interface IGlobalApplicationEventsPlugin
          Inherits IPlugin
  extensionMethods:
  - SuperOffice.Events.IGlobalApplicationEventsPlugin.EnumUtil.MapEnums``2
  - SuperOffice.Events.IGlobalApplicationEventsPlugin.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start(System.Web.HttpApplication,System.Object,System.EventArgs)
  commentId: M:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start(System.Web.HttpApplication,System.Object,System.EventArgs)
  id: Application_Start(System.Web.HttpApplication,System.Object,System.EventArgs)
  parent: SuperOffice.Events.IGlobalApplicationEventsPlugin
  langs:
  - csharp
  - vb
  name: Application_Start(HttpApplication, Object, EventArgs)
  nameWithType: IGlobalApplicationEventsPlugin.Application_Start(HttpApplication, Object, EventArgs)
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start(System.Web.HttpApplication, System.Object, System.EventArgs)
  type: Method
  source:
    path: SOCore
    isExternal: true
  assemblies:
  - SOCore
  namespace: SuperOffice.Events
  summary: "\nHandle Application_start from global.asax\n"
  syntax:
    content: void Application_Start(HttpApplication application, object sender, EventArgs e)
    parameters:
    - id: application
      type: System.Web.HttpApplication
      description: Application sending the event.
    - id: sender
      type: System.Object
    - id: e
      type: System.EventArgs
    content.vb: Sub Application_Start(application As HttpApplication, sender As Object, e As EventArgs)
  overload: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start*
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error(System.Web.HttpApplication,System.Object,System.EventArgs)
  commentId: M:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error(System.Web.HttpApplication,System.Object,System.EventArgs)
  id: Application_Error(System.Web.HttpApplication,System.Object,System.EventArgs)
  parent: SuperOffice.Events.IGlobalApplicationEventsPlugin
  langs:
  - csharp
  - vb
  name: Application_Error(HttpApplication, Object, EventArgs)
  nameWithType: IGlobalApplicationEventsPlugin.Application_Error(HttpApplication, Object, EventArgs)
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error(System.Web.HttpApplication, System.Object, System.EventArgs)
  type: Method
  source:
    path: SOCore
    isExternal: true
  assemblies:
  - SOCore
  namespace: SuperOffice.Events
  summary: "\nHandle Application_Error from global.asax\n"
  syntax:
    content: void Application_Error(HttpApplication application, object sender, EventArgs e)
    parameters:
    - id: application
      type: System.Web.HttpApplication
      description: Application sending the event.
    - id: sender
      type: System.Object
    - id: e
      type: System.EventArgs
    content.vb: Sub Application_Error(application As HttpApplication, sender As Object, e As EventArgs)
  overload: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error*
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End(System.Web.HttpApplication,System.Object,System.EventArgs)
  commentId: M:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End(System.Web.HttpApplication,System.Object,System.EventArgs)
  id: Application_End(System.Web.HttpApplication,System.Object,System.EventArgs)
  parent: SuperOffice.Events.IGlobalApplicationEventsPlugin
  langs:
  - csharp
  - vb
  name: Application_End(HttpApplication, Object, EventArgs)
  nameWithType: IGlobalApplicationEventsPlugin.Application_End(HttpApplication, Object, EventArgs)
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End(System.Web.HttpApplication, System.Object, System.EventArgs)
  type: Method
  source:
    path: SOCore
    isExternal: true
  assemblies:
  - SOCore
  namespace: SuperOffice.Events
  summary: "\nHandle Application_End from global.asax\n"
  syntax:
    content: void Application_End(HttpApplication application, object sender, EventArgs e)
    parameters:
    - id: application
      type: System.Web.HttpApplication
      description: Application sending the event.
    - id: sender
      type: System.Object
    - id: e
      type: System.EventArgs
    content.vb: Sub Application_End(application As HttpApplication, sender As Object, e As EventArgs)
  overload: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End*
references:
- uid: SuperOffice.Events
  commentId: N:SuperOffice.Events
  isExternal: true
  name: SuperOffice.Events
  nameWithType: SuperOffice.Events
  fullName: SuperOffice.Events
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<IGlobalApplicationEventsPlugin, To>()
  nameWithType: EnumUtil.MapEnums<IGlobalApplicationEventsPlugin, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.Events.IGlobalApplicationEventsPlugin, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of IGlobalApplicationEventsPlugin, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.Events.IGlobalApplicationEventsPlugin, To)()
  name.vb: MapEnums(Of IGlobalApplicationEventsPlugin, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<IGlobalApplicationEventsPlugin, To>
    nameWithType: EnumUtil.MapEnums<IGlobalApplicationEventsPlugin, To>
    fullName: EnumUtil.MapEnums<SuperOffice.Events.IGlobalApplicationEventsPlugin, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of IGlobalApplicationEventsPlugin, To)
    nameWithType: EnumUtil.MapEnums(Of IGlobalApplicationEventsPlugin, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.Events.IGlobalApplicationEventsPlugin, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<IGlobalApplicationEventsPlugin, To>()
  nameWithType: Converters.MapEnums<IGlobalApplicationEventsPlugin, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.Events.IGlobalApplicationEventsPlugin, To>()
  nameWithType.vb: Converters.MapEnums(Of IGlobalApplicationEventsPlugin, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.Events.IGlobalApplicationEventsPlugin, To)()
  name.vb: MapEnums(Of IGlobalApplicationEventsPlugin, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<IGlobalApplicationEventsPlugin, To>
    nameWithType: Converters.MapEnums<IGlobalApplicationEventsPlugin, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.Events.IGlobalApplicationEventsPlugin, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of IGlobalApplicationEventsPlugin, To)
    nameWithType: Converters.MapEnums(Of IGlobalApplicationEventsPlugin, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.Events.IGlobalApplicationEventsPlugin, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start*
  commentId: Overload:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start
  isExternal: true
  name: Application_Start
  nameWithType: IGlobalApplicationEventsPlugin.Application_Start
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Start
- uid: System.Web.HttpApplication
  isExternal: true
  name: HttpApplication
  nameWithType: HttpApplication
  fullName: System.Web.HttpApplication
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error*
  commentId: Overload:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error
  isExternal: true
  name: Application_Error
  nameWithType: IGlobalApplicationEventsPlugin.Application_Error
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_Error
- uid: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End*
  commentId: Overload:SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End
  isExternal: true
  name: Application_End
  nameWithType: IGlobalApplicationEventsPlugin.Application_End
  fullName: SuperOffice.Events.IGlobalApplicationEventsPlugin.Application_End
