### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Mail.Component
  commentId: T:SuperOffice.Configuration.ConfigFile.Mail.Component
  id: ConfigFile.Mail.Component
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
  langs:
  - csharp
  - vb
  name: ConfigFile.Mail.Component
  nameWithType: ConfigFile.Mail.Component
  fullName: SuperOffice.Configuration.ConfigFile.Mail.Component
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nMail component options\n"
  syntax:
    content: 'public static class Component : Object'
    content.vb: >-
      Public Module Component

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
  commentId: P:SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
  id: NumberOfDaysToDownload
  parent: SuperOffice.Configuration.ConfigFile.Mail.Component
  langs:
  - csharp
  - vb
  name: NumberOfDaysToDownload
  nameWithType: ConfigFile.Mail.Component.NumberOfDaysToDownload
  fullName: SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nInitial number of days to fetch mail for\n"
  syntax:
    content: public static int NumberOfDaysToDownload { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property NumberOfDaysToDownload As Integer
  overload: SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
  isExternal: true
  name: NumberOfDaysToDownload
  nameWithType: ConfigFile.Mail.Component.NumberOfDaysToDownload
  fullName: SuperOffice.Configuration.ConfigFile.Mail.Component.NumberOfDaysToDownload
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
