### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  commentId: T:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  id: ConfigFile.Security.SoPasswordCredentialPlugin
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  - SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  - SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  - SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  langs:
  - csharp
  - vb
  name: ConfigFile.Security.SoPasswordCredentialPlugin
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class SoPasswordCredentialPlugin : Object'
    content.vb: >-
      Public Module SoPasswordCredentialPlugin

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  id: DisableUseInternalAssociate
  parent: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  langs:
  - csharp
  - vb
  name: DisableUseInternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nDisables SuperOffice-passwords for Internal associates (normal users).\n"
  syntax:
    content: public static bool DisableUseInternalAssociate { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DisableUseInternalAssociate As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  id: DisableUseSystemAssociate
  parent: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  langs:
  - csharp
  - vb
  name: DisableUseSystemAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nDisables SuperOffice password for System associates.\n"
  syntax:
    content: public static bool DisableUseSystemAssociate { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DisableUseSystemAssociate As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  id: DisableUseExternalAssociate
  parent: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  langs:
  - csharp
  - vb
  name: DisableUseExternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nDisables SuperOffice password for External associates.\n"
  syntax:
    content: public static bool DisableUseExternalAssociate { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DisableUseExternalAssociate As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  id: PriorityInternalAssociate
  parent: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin
  langs:
  - csharp
  - vb
  name: PriorityInternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nPriority of the plugin for internal associates.\n"
  syntax:
    content: public static int PriorityInternalAssociate { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property PriorityInternalAssociate As Integer
  overload: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  isExternal: true
  name: DisableUseInternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseInternalAssociate
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  isExternal: true
  name: DisableUseSystemAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseSystemAssociate
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  isExternal: true
  name: DisableUseExternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.DisableUseExternalAssociate
- uid: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  isExternal: true
  name: PriorityInternalAssociate
  nameWithType: ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
  fullName: SuperOffice.Configuration.ConfigFile.Security.SoPasswordCredentialPlugin.PriorityInternalAssociate
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
