### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings
  commentId: T:SuperOffice.CRM.Workflow.RemoveFromListSettings
  id: RemoveFromListSettings
  parent: SuperOffice.CRM.Workflow
  children:
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
  langs:
  - csharp
  - vb
  name: RemoveFromListSettings
  nameWithType: RemoveFromListSettings
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings
  type: Class
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Workflow
  syntax:
    content: 'public class RemoveFromListSettings : StepSettings'
    content.vb: >-
      Public Class RemoveFromListSettings

          Inherits StepSettings
  inheritance:
  - System.Object
  - SuperOffice.CRM.Workflow.StepSettings
  extensionMethods:
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.EnumUtil.MapEnums``2
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.Util.ObjectExtensions.AssignByReflection``1(SuperOffice.CRM.Workflow.RemoveFromListSettings)
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.Util.ObjectExtensions.GraphCopy``1
  - SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor
  commentId: M:SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Workflow.RemoveFromListSettings
  langs:
  - csharp
  - vb
  name: RemoveFromListSettings()
  nameWithType: RemoveFromListSettings.RemoveFromListSettings()
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.RemoveFromListSettings()
  type: Constructor
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Workflow
  syntax:
    content: public RemoveFromListSettings()
    content.vb: Public Sub New
  overload: SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
  commentId: P:SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
  id: Selection
  parent: SuperOffice.CRM.Workflow.RemoveFromListSettings
  langs:
  - csharp
  - vb
  name: Selection
  nameWithType: RemoveFromListSettings.Selection
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
  type: Property
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Workflow
  syntax:
    content: public int Selection { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Selection As Integer
  overload: SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
  commentId: P:SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
  id: Project
  parent: SuperOffice.CRM.Workflow.RemoveFromListSettings
  langs:
  - csharp
  - vb
  name: Project
  nameWithType: RemoveFromListSettings.Project
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
  type: Property
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Workflow
  syntax:
    content: public int Project { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Project As Integer
  overload: SuperOffice.CRM.Workflow.RemoveFromListSettings.Project*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: SuperOffice.CRM.Workflow
  commentId: N:SuperOffice.CRM.Workflow
  isExternal: true
  name: SuperOffice.CRM.Workflow
  nameWithType: SuperOffice.CRM.Workflow
  fullName: SuperOffice.CRM.Workflow
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.CRM.Workflow.StepSettings
  commentId: T:SuperOffice.CRM.Workflow.StepSettings
  parent: SuperOffice.CRM.Workflow
  isExternal: true
  name: StepSettings
  nameWithType: StepSettings
  fullName: SuperOffice.CRM.Workflow.StepSettings
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<RemoveFromListSettings, To>()
  nameWithType: EnumUtil.MapEnums<RemoveFromListSettings, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.CRM.Workflow.RemoveFromListSettings, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of RemoveFromListSettings, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.CRM.Workflow.RemoveFromListSettings, To)()
  name.vb: MapEnums(Of RemoveFromListSettings, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<RemoveFromListSettings, To>
    nameWithType: EnumUtil.MapEnums<RemoveFromListSettings, To>
    fullName: EnumUtil.MapEnums<SuperOffice.CRM.Workflow.RemoveFromListSettings, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of RemoveFromListSettings, To)
    nameWithType: EnumUtil.MapEnums(Of RemoveFromListSettings, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.CRM.Workflow.RemoveFromListSettings, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.Util.ObjectExtensions.AssignByReflection``1(SuperOffice.CRM.Workflow.RemoveFromListSettings)
  commentId: M:SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  parent: SuperOffice.Util.ObjectExtensions
  definition: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  name: AssignByReflection<RemoveFromListSettings>(RemoveFromListSettings)
  nameWithType: ObjectExtensions.AssignByReflection<RemoveFromListSettings>(RemoveFromListSettings)
  fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<SuperOffice.CRM.Workflow.RemoveFromListSettings>(SuperOffice.CRM.Workflow.RemoveFromListSettings)
  nameWithType.vb: ObjectExtensions.AssignByReflection(Of RemoveFromListSettings)(RemoveFromListSettings)
  fullName.vb: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of SuperOffice.CRM.Workflow.RemoveFromListSettings)(SuperOffice.CRM.Workflow.RemoveFromListSettings)
  name.vb: AssignByReflection(Of RemoveFromListSettings)(RemoveFromListSettings)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0)
    name: AssignByReflection<RemoveFromListSettings>
    nameWithType: ObjectExtensions.AssignByReflection<RemoveFromListSettings>
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<SuperOffice.CRM.Workflow.RemoveFromListSettings>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: SuperOffice.CRM.Workflow.RemoveFromListSettings
    name: RemoveFromListSettings
    nameWithType: RemoveFromListSettings
    fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0)
    name: AssignByReflection(Of RemoveFromListSettings)
    nameWithType: ObjectExtensions.AssignByReflection(Of RemoveFromListSettings)
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of SuperOffice.CRM.Workflow.RemoveFromListSettings)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: SuperOffice.CRM.Workflow.RemoveFromListSettings
    name: RemoveFromListSettings
    nameWithType: RemoveFromListSettings
    fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.Util.ObjectExtensions.GraphCopy``1
  commentId: M:SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  parent: SuperOffice.Util.ObjectExtensions
  definition: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  name: GraphCopy<RemoveFromListSettings>()
  nameWithType: ObjectExtensions.GraphCopy<RemoveFromListSettings>()
  fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<SuperOffice.CRM.Workflow.RemoveFromListSettings>()
  nameWithType.vb: ObjectExtensions.GraphCopy(Of RemoveFromListSettings)()
  fullName.vb: SuperOffice.Util.ObjectExtensions.GraphCopy(Of SuperOffice.CRM.Workflow.RemoveFromListSettings)()
  name.vb: GraphCopy(Of RemoveFromListSettings)()
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1
    name: GraphCopy<RemoveFromListSettings>
    nameWithType: ObjectExtensions.GraphCopy<RemoveFromListSettings>
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<SuperOffice.CRM.Workflow.RemoveFromListSettings>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1
    name: GraphCopy(Of RemoveFromListSettings)
    nameWithType: ObjectExtensions.GraphCopy(Of RemoveFromListSettings)
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy(Of SuperOffice.CRM.Workflow.RemoveFromListSettings)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<RemoveFromListSettings, To>()
  nameWithType: Converters.MapEnums<RemoveFromListSettings, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.CRM.Workflow.RemoveFromListSettings, To>()
  nameWithType.vb: Converters.MapEnums(Of RemoveFromListSettings, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.CRM.Workflow.RemoveFromListSettings, To)()
  name.vb: MapEnums(Of RemoveFromListSettings, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<RemoveFromListSettings, To>
    nameWithType: Converters.MapEnums<RemoveFromListSettings, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.CRM.Workflow.RemoveFromListSettings, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of RemoveFromListSettings, To)
    nameWithType: Converters.MapEnums(Of RemoveFromListSettings, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.CRM.Workflow.RemoveFromListSettings, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  commentId: M:SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  isExternal: true
  name: AssignByReflection<T>(T, T)
  nameWithType: ObjectExtensions.AssignByReflection<T>(T, T)
  fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<T>(T, T)
  nameWithType.vb: ObjectExtensions.AssignByReflection(Of T)(T, T)
  fullName.vb: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of T)(T, T)
  name.vb: AssignByReflection(Of T)(T, T)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
    name: AssignByReflection<T>
    nameWithType: ObjectExtensions.AssignByReflection<T>
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
    name: AssignByReflection(Of T)
    nameWithType: ObjectExtensions.AssignByReflection(Of T)
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.Util.ObjectExtensions
  commentId: T:SuperOffice.Util.ObjectExtensions
  parent: SuperOffice.Util
  isExternal: true
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: SuperOffice.Util.ObjectExtensions
- uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  commentId: M:SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  isExternal: true
  name: GraphCopy<T>(T)
  nameWithType: ObjectExtensions.GraphCopy<T>(T)
  fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<T>(T)
  nameWithType.vb: ObjectExtensions.GraphCopy(Of T)(T)
  fullName.vb: SuperOffice.Util.ObjectExtensions.GraphCopy(Of T)(T)
  name.vb: GraphCopy(Of T)(T)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
    name: GraphCopy<T>
    nameWithType: ObjectExtensions.GraphCopy<T>
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
    name: GraphCopy(Of T)
    nameWithType: ObjectExtensions.GraphCopy(Of T)
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.Util
  commentId: N:SuperOffice.Util
  isExternal: true
  name: SuperOffice.Util
  nameWithType: SuperOffice.Util
  fullName: SuperOffice.Util
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor*
  commentId: Overload:SuperOffice.CRM.Workflow.RemoveFromListSettings.#ctor
  isExternal: true
  name: RemoveFromListSettings
  nameWithType: RemoveFromListSettings.RemoveFromListSettings
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.RemoveFromListSettings
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection*
  commentId: Overload:SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
  isExternal: true
  name: Selection
  nameWithType: RemoveFromListSettings.Selection
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.Selection
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.CRM.Workflow.RemoveFromListSettings.Project*
  commentId: Overload:SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
  isExternal: true
  name: Project
  nameWithType: RemoveFromListSettings.Project
  fullName: SuperOffice.CRM.Workflow.RemoveFromListSettings.Project
