### YamlMime:ManagedReference
items:
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config
  commentId: T:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config
  id: ConfigurationAttributes.ControlElements.Config
  parent: SuperOffice.DCF.Configuration
  children:
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.ConfigAttribute
  langs:
  - csharp
  - vb
  name: ConfigurationAttributes.ControlElements.Config
  nameWithType: ConfigurationAttributes.ControlElements.Config
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class Config : Object'
    content.vb: >-
      Public Module Config

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.ConfigAttribute
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.ConfigAttribute
  id: ConfigAttribute
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config
  langs:
  - csharp
  - vb
  name: ConfigAttribute
  nameWithType: ConfigurationAttributes.ControlElements.Config.ConfigAttribute
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.ConfigAttribute
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string ConfigAttribute = "config"
    return:
      type: System.String
    content.vb: Public Const ConfigAttribute As String = "config"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.DCF.Configuration
  commentId: N:SuperOffice.DCF.Configuration
  isExternal: true
  name: SuperOffice.DCF.Configuration
  nameWithType: SuperOffice.DCF.Configuration
  fullName: SuperOffice.DCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
