### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Services
  commentId: T:SuperOffice.Configuration.ConfigFile.Services
  id: ConfigFile.Services
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
  - SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
  langs:
  - csharp
  - vb
  name: ConfigFile.Services
  nameWithType: ConfigFile.Services
  fullName: SuperOffice.Configuration.ConfigFile.Services
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUtility class used to access the SuperOffice.CRM.Services entry in the Config file.\n"
  syntax:
    content: 'public static class Services : Object'
    content.vb: >-
      Public Module Services

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
  commentId: P:SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
  id: RemoteBaseURL
  parent: SuperOffice.Configuration.ConfigFile.Services
  langs:
  - csharp
  - vb
  name: RemoteBaseURL
  nameWithType: ConfigFile.Services.RemoteBaseURL
  fullName: SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nBase URL for remote services (Default: http://localhost/webs/SuperOffice.Web.Services).  This value will be overridden by WebServices.RemoteBaseURL\n"
  syntax:
    content: public static string RemoteBaseURL { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property RemoteBaseURL As String
  overload: SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
  commentId: P:SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
  id: ApplicationToken
  parent: SuperOffice.Configuration.ConfigFile.Services
  langs:
  - csharp
  - vb
  name: ApplicationToken
  nameWithType: ConfigFile.Services.ApplicationToken
  fullName: SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nApplication token passed with servicves to identify the client application.\n"
  syntax:
    content: public static string ApplicationToken { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ApplicationToken As String
  overload: SuperOffice.Configuration.ConfigFile.Services.ApplicationToken*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
  isExternal: true
  name: RemoteBaseURL
  nameWithType: ConfigFile.Services.RemoteBaseURL
  fullName: SuperOffice.Configuration.ConfigFile.Services.RemoteBaseURL
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Services.ApplicationToken*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
  isExternal: true
  name: ApplicationToken
  nameWithType: ConfigFile.Services.ApplicationToken
  fullName: SuperOffice.Configuration.ConfigFile.Services.ApplicationToken
