### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography
  commentId: T:SuperOffice.Configuration.ConfigFile.Security.Cryptography
  id: ConfigFile.Security.Cryptography
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
  - SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
  - SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
  langs:
  - csharp
  - vb
  name: ConfigFile.Security.Cryptography
  nameWithType: ConfigFile.Security.Cryptography
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nCryptographic options\n"
  syntax:
    content: 'public static class Cryptography : Object'
    content.vb: >-
      Public Module Cryptography

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
  id: SymmetricKey
  parent: SuperOffice.Configuration.ConfigFile.Security.Cryptography
  langs:
  - csharp
  - vb
  name: SymmetricKey
  nameWithType: ConfigFile.Security.Cryptography.SymmetricKey
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe Key used in the Rijndael algorithm\n"
  syntax:
    content: public static string SymmetricKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property SymmetricKey As String
  overload: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
  id: SymmetricIV
  parent: SuperOffice.Configuration.ConfigFile.Security.Cryptography
  langs:
  - csharp
  - vb
  name: SymmetricIV
  nameWithType: ConfigFile.Security.Cryptography.SymmetricIV
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe IV used in the Rijndael algorithm\n"
  syntax:
    content: public static string SymmetricIV { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property SymmetricIV As String
  overload: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
  id: SymmetricSecret
  parent: SuperOffice.Configuration.ConfigFile.Security.Cryptography
  langs:
  - csharp
  - vb
  name: SymmetricSecret
  nameWithType: ConfigFile.Security.Cryptography.SymmetricSecret
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nA secret phrase used as a signature\n"
  syntax:
    content: public static string SymmetricSecret { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property SymmetricSecret As String
  overload: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
  isExternal: true
  name: SymmetricKey
  nameWithType: ConfigFile.Security.Cryptography.SymmetricKey
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
  isExternal: true
  name: SymmetricIV
  nameWithType: ConfigFile.Security.Cryptography.SymmetricIV
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricIV
- uid: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
  isExternal: true
  name: SymmetricSecret
  nameWithType: ConfigFile.Security.Cryptography.SymmetricSecret
  fullName: SuperOffice.Configuration.ConfigFile.Security.Cryptography.SymmetricSecret
