### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Security.Sentry
  commentId: T:SuperOffice.Configuration.ConfigFile.Security.Sentry
  id: ConfigFile.Security.Sentry
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
  langs:
  - csharp
  - vb
  name: ConfigFile.Security.Sentry
  nameWithType: ConfigFile.Security.Sentry
  fullName: SuperOffice.Configuration.ConfigFile.Security.Sentry
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nSentry configuration\n"
  syntax:
    content: 'public static class Sentry : Object'
    content.vb: >-
      Public Module Sentry

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
  commentId: P:SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
  id: Ignore
  parent: SuperOffice.Configuration.ConfigFile.Security.Sentry
  langs:
  - csharp
  - vb
  name: Ignore
  nameWithType: ConfigFile.Security.Sentry.Ignore
  fullName: SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nIgnore the Sentry mechanism, everything will be allowed (default &apos;False&apos;)\n"
  remarks: "\nThis option is only available in SuperOffice NetServer version 1.0. The reason for permitting it here is that the Sentry mechanism is rather new, and disabeling it is the last resort in case of severe problems.\n"
  syntax:
    content: public static bool Ignore { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property Ignore As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
  isExternal: true
  name: Ignore
  nameWithType: ConfigFile.Security.Sentry.Ignore
  fullName: SuperOffice.Configuration.ConfigFile.Security.Sentry.Ignore
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
