### YamlMime:ManagedReference
items:
- uid: SuperOffice.Data.ConfigType
  commentId: T:SuperOffice.Data.ConfigType
  id: ConfigType
  parent: SuperOffice.Data
  children:
  - SuperOffice.Data.ConfigType.Options
  - SuperOffice.Data.ConfigType.Style
  - SuperOffice.Data.ConfigType.value__
  langs:
  - csharp
  - vb
  name: ConfigType
  nameWithType: ConfigType
  fullName: SuperOffice.Data.ConfigType
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Data
  summary: "\nValue for field &apos;type&apos; in table &apos;cust_config&apos;.\nThis Enum is used by:  cust_config.type\n"
  syntax:
    content: 'public sealed class ConfigType : Enum'
    content.vb: >-
      Public NotInheritable Class ConfigType

          Inherits



           Enum
  inheritance:
  - System.Object
  extensionMethods:
  - SuperOffice.Data.ConfigType.EnumUtil.MapEnums``2
  - SuperOffice.Data.ConfigType.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: SuperOffice.Data.ConfigType.value__
  commentId: F:SuperOffice.Data.ConfigType.value__
  id: value__
  parent: SuperOffice.Data.ConfigType
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: ConfigType.value__
  fullName: SuperOffice.Data.ConfigType.value__
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Data
  syntax:
    content: public short value__
    return:
      type: System.Int16
    content.vb: Public value__ As Short
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.Data.ConfigType.Style
  commentId: F:SuperOffice.Data.ConfigType.Style
  id: Style
  parent: SuperOffice.Data.ConfigType
  langs:
  - csharp
  - vb
  name: Style
  nameWithType: ConfigType.Style
  fullName: SuperOffice.Data.ConfigType.Style
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Data
  summary: "\n0: The row contains style data\n"
  syntax:
    content: public const ConfigType Style
    return:
      type: SuperOffice.Data.ConfigType
    content.vb: Public Const Style As ConfigType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.Data.ConfigType.Options
  commentId: F:SuperOffice.Data.ConfigType.Options
  id: Options
  parent: SuperOffice.Data.ConfigType
  langs:
  - csharp
  - vb
  name: Options
  nameWithType: ConfigType.Options
  fullName: SuperOffice.Data.ConfigType.Options
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Data
  summary: "\n1: The row contains options data\n"
  syntax:
    content: public const ConfigType Options
    return:
      type: SuperOffice.Data.ConfigType
    content.vb: Public Const Options As ConfigType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.Data
  commentId: N:SuperOffice.Data
  isExternal: true
  name: SuperOffice.Data
  nameWithType: SuperOffice.Data
  fullName: SuperOffice.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.Data.ConfigType.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<ConfigType, To>()
  nameWithType: EnumUtil.MapEnums<ConfigType, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.Data.ConfigType, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of ConfigType, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.Data.ConfigType, To)()
  name.vb: MapEnums(Of ConfigType, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<ConfigType, To>
    nameWithType: EnumUtil.MapEnums<ConfigType, To>
    fullName: EnumUtil.MapEnums<SuperOffice.Data.ConfigType, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of ConfigType, To)
    nameWithType: EnumUtil.MapEnums(Of ConfigType, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.Data.ConfigType, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.Data.ConfigType.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<ConfigType, To>()
  nameWithType: Converters.MapEnums<ConfigType, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.Data.ConfigType, To>()
  nameWithType.vb: Converters.MapEnums(Of ConfigType, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.Data.ConfigType, To)()
  name.vb: MapEnums(Of ConfigType, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<ConfigType, To>
    nameWithType: Converters.MapEnums<ConfigType, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.Data.ConfigType, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of ConfigType, To)
    nameWithType: Converters.MapEnums(Of ConfigType, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.Data.ConfigType, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: System.Int16
  commentId: T:System.Int16
  parent: System
  isExternal: true
  name: Int16
  nameWithType: Int16
  fullName: System.Int16
- uid: SuperOffice.Data.ConfigType
  commentId: T:SuperOffice.Data.ConfigType
  parent: SuperOffice.Data
  isExternal: true
  name: ConfigType
  nameWithType: ConfigType
  fullName: SuperOffice.Data.ConfigType
