### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Threading
  commentId: T:SuperOffice.Configuration.ConfigFile.Threading
  id: ConfigFile.Threading
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
  - SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
  - SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
  langs:
  - csharp
  - vb
  name: ConfigFile.Threading
  nameWithType: ConfigFile.Threading
  fullName: SuperOffice.Configuration.ConfigFile.Threading
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to threading.\n"
  syntax:
    content: 'public static class Threading : Object'
    content.vb: >-
      Public Module Threading

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
  commentId: P:SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
  id: MaxParellalThreads
  parent: SuperOffice.Configuration.ConfigFile.Threading
  langs:
  - csharp
  - vb
  name: MaxParellalThreads
  nameWithType: ConfigFile.Threading.MaxParellalThreads
  fullName: SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nMax parallel operations that is permitted to be run in parallel.  -1 is infinite and 30 is default.\n"
  syntax:
    content: public static int MaxParellalThreads { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxParellalThreads As Integer
  overload: SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
  commentId: P:SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
  id: DisableMultithreading
  parent: SuperOffice.Configuration.ConfigFile.Threading
  langs:
  - csharp
  - vb
  name: DisableMultithreading
  nameWithType: ConfigFile.Threading.DisableMultithreading
  fullName: SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static bool DisableMultithreading { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property DisableMultithreading As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
  commentId: P:SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
  id: ForceMultithreading
  parent: SuperOffice.Configuration.ConfigFile.Threading
  langs:
  - csharp
  - vb
  name: ForceMultithreading
  nameWithType: ConfigFile.Threading.ForceMultithreading
  fullName: SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static bool ForceMultithreading { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property ForceMultithreading As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
  isExternal: true
  name: MaxParellalThreads
  nameWithType: ConfigFile.Threading.MaxParellalThreads
  fullName: SuperOffice.Configuration.ConfigFile.Threading.MaxParellalThreads
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
  isExternal: true
  name: DisableMultithreading
  nameWithType: ConfigFile.Threading.DisableMultithreading
  fullName: SuperOffice.Configuration.ConfigFile.Threading.DisableMultithreading
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
  isExternal: true
  name: ForceMultithreading
  nameWithType: ConfigFile.Threading.ForceMultithreading
  fullName: SuperOffice.Configuration.ConfigFile.Threading.ForceMultithreading
