### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.FeatureToggles
  commentId: T:SuperOffice.Configuration.ConfigFile.FeatureToggles
  id: ConfigFile.FeatureToggles
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.FeatureToggles.State
  langs:
  - csharp
  - vb
  name: ConfigFile.FeatureToggles
  nameWithType: ConfigFile.FeatureToggles
  fullName: SuperOffice.Configuration.ConfigFile.FeatureToggles
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nValues for Feature Toggles; see the SuperOffice.FeatureToggles.dll assembly for definitions. Toggles not mentioned here will be OFF\n"
  syntax:
    content: 'public static class FeatureToggles : Object'
    content.vb: >-
      Public Module FeatureToggles

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.FeatureToggles.State
  commentId: P:SuperOffice.Configuration.ConfigFile.FeatureToggles.State
  id: State
  parent: SuperOffice.Configuration.ConfigFile.FeatureToggles
  langs:
  - csharp
  - vb
  name: State
  nameWithType: ConfigFile.FeatureToggles.State
  fullName: SuperOffice.Configuration.ConfigFile.FeatureToggles.State
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nAdd feature toggle name to value (True/False) for toggles you wish to set\n"
  syntax:
    content: public static NameValueCollection State { get; }
    parameters: []
    return:
      type: System.Collections.Specialized.NameValueCollection
    content.vb: Public Shared ReadOnly Property State As NameValueCollection
  overload: SuperOffice.Configuration.ConfigFile.FeatureToggles.State*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.FeatureToggles.State*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.FeatureToggles.State
  isExternal: true
  name: State
  nameWithType: ConfigFile.FeatureToggles.State
  fullName: SuperOffice.Configuration.ConfigFile.FeatureToggles.State
- uid: System.Collections.Specialized.NameValueCollection
  isExternal: true
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
