### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Scripting
  commentId: T:SuperOffice.Configuration.ConfigFile.Scripting
  id: ConfigFile.Scripting
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
  - SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
  - SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
  - SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
  langs:
  - csharp
  - vb
  name: ConfigFile.Scripting
  nameWithType: ConfigFile.Scripting
  fullName: SuperOffice.Configuration.ConfigFile.Scripting
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class Scripting : Object'
    content.vb: >-
      Public Module Scripting

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
  commentId: P:SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
  id: ScriptPath
  parent: SuperOffice.Configuration.ConfigFile.Scripting
  langs:
  - csharp
  - vb
  name: ScriptPath
  nameWithType: ConfigFile.Scripting.ScriptPath
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static string ScriptPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ScriptPath As String
  overload: SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
  commentId: P:SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
  id: EnableScripting
  parent: SuperOffice.Configuration.ConfigFile.Scripting
  langs:
  - csharp
  - vb
  name: EnableScripting
  nameWithType: ConfigFile.Scripting.EnableScripting
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static bool EnableScripting { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property EnableScripting As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
  commentId: P:SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
  id: TimeoutLimit
  parent: SuperOffice.Configuration.ConfigFile.Scripting
  langs:
  - csharp
  - vb
  name: TimeoutLimit
  nameWithType: ConfigFile.Scripting.TimeoutLimit
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static int TimeoutLimit { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property TimeoutLimit As Integer
  overload: SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
  commentId: P:SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
  id: MaxTimeouts
  parent: SuperOffice.Configuration.ConfigFile.Scripting
  langs:
  - csharp
  - vb
  name: MaxTimeouts
  nameWithType: ConfigFile.Scripting.MaxTimeouts
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\n\n"
  syntax:
    content: public static int MaxTimeouts { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxTimeouts As Integer
  overload: SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
  isExternal: true
  name: ScriptPath
  nameWithType: ConfigFile.Scripting.ScriptPath
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.ScriptPath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
  isExternal: true
  name: EnableScripting
  nameWithType: ConfigFile.Scripting.EnableScripting
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.EnableScripting
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
  isExternal: true
  name: TimeoutLimit
  nameWithType: ConfigFile.Scripting.TimeoutLimit
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.TimeoutLimit
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
  isExternal: true
  name: MaxTimeouts
  nameWithType: ConfigFile.Scripting.MaxTimeouts
  fullName: SuperOffice.Configuration.ConfigFile.Scripting.MaxTimeouts
