### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.SuspendedSite
  commentId: T:SuperOffice.Configuration.ConfigFile.SuspendedSite
  id: ConfigFile.SuspendedSite
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
  - SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
  langs:
  - csharp
  - vb
  name: ConfigFile.SuspendedSite
  nameWithType: ConfigFile.SuspendedSite
  fullName: SuperOffice.Configuration.ConfigFile.SuspendedSite
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to Suspended state.\n"
  syntax:
    content: 'public static class SuspendedSite : Object'
    content.vb: >-
      Public Module SuspendedSite

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
  commentId: P:SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
  id: suspended
  parent: SuperOffice.Configuration.ConfigFile.SuspendedSite
  langs:
  - csharp
  - vb
  name: suspended
  nameWithType: ConfigFile.SuspendedSite.suspended
  fullName: SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe current state of the site.\n"
  syntax:
    content: public static bool suspended { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property suspended As Boolean
  overload: SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
  commentId: P:SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
  id: download_baseurl
  parent: SuperOffice.Configuration.ConfigFile.SuspendedSite
  langs:
  - csharp
  - vb
  name: download_baseurl
  nameWithType: ConfigFile.SuspendedSite.download_baseurl
  fullName: SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nDownload base url\n"
  syntax:
    content: public static string download_baseurl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property download_baseurl As String
  overload: SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
  isExternal: true
  name: suspended
  nameWithType: ConfigFile.SuspendedSite.suspended
  fullName: SuperOffice.Configuration.ConfigFile.SuspendedSite.suspended
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
  isExternal: true
  name: download_baseurl
  nameWithType: ConfigFile.SuspendedSite.download_baseurl
  fullName: SuperOffice.Configuration.ConfigFile.SuspendedSite.download_baseurl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
