### YamlMime:ManagedReference
items:
- uid: SuperOffice.IO.Files.SoArcConfiguration
  commentId: T:SuperOffice.IO.Files.SoArcConfiguration
  id: SoArcConfiguration
  parent: SuperOffice.IO.Files
  children:
  - SuperOffice.IO.Files.SoArcConfiguration.#ctor
  - SuperOffice.IO.Files.SoArcConfiguration.SectionName
  - SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
  langs:
  - csharp
  - vb
  name: SoArcConfiguration
  nameWithType: SoArcConfiguration
  fullName: SuperOffice.IO.Files.SoArcConfiguration
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.IO.Files
  syntax:
    content: 'public class SoArcConfiguration : Object'
    content.vb: >-
      Public Class SoArcConfiguration

          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - SuperOffice.IO.Files.SoArcConfiguration.EnumUtil.MapEnums``2
  - SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.Util.ObjectExtensions.AssignByReflection``1(SuperOffice.IO.Files.SoArcConfiguration)
  - SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.Util.ObjectExtensions.GraphCopy``1
  - SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.IO.Files.SoArcConfiguration.SectionName
  commentId: F:SuperOffice.IO.Files.SoArcConfiguration.SectionName
  id: SectionName
  parent: SuperOffice.IO.Files.SoArcConfiguration
  langs:
  - csharp
  - vb
  name: SectionName
  nameWithType: SoArcConfiguration.SectionName
  fullName: SuperOffice.IO.Files.SoArcConfiguration.SectionName
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.IO.Files
  syntax:
    content: public const string SectionName = "SoArc"
    return:
      type: System.String
    content.vb: Public Const SectionName As String = "SoArc"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.IO.Files.SoArcConfiguration.#ctor
  commentId: M:SuperOffice.IO.Files.SoArcConfiguration.#ctor
  id: '#ctor'
  parent: SuperOffice.IO.Files.SoArcConfiguration
  langs:
  - csharp
  - vb
  name: SoArcConfiguration()
  nameWithType: SoArcConfiguration.SoArcConfiguration()
  fullName: SuperOffice.IO.Files.SoArcConfiguration.SoArcConfiguration()
  type: Constructor
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.IO.Files
  syntax:
    content: public SoArcConfiguration()
    content.vb: Public Sub New
  overload: SuperOffice.IO.Files.SoArcConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
  commentId: P:SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
  id: UseAzureBlobStorage
  parent: SuperOffice.IO.Files.SoArcConfiguration
  langs:
  - csharp
  - vb
  name: UseAzureBlobStorage
  nameWithType: SoArcConfiguration.UseAzureBlobStorage
  fullName: SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.IO.Files
  syntax:
    content: public bool UseAzureBlobStorage { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property UseAzureBlobStorage As Boolean
  overload: SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: SuperOffice.IO.Files
  commentId: N:SuperOffice.IO.Files
  isExternal: true
  name: SuperOffice.IO.Files
  nameWithType: SuperOffice.IO.Files
  fullName: SuperOffice.IO.Files
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.IO.Files.SoArcConfiguration.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<SoArcConfiguration, To>()
  nameWithType: EnumUtil.MapEnums<SoArcConfiguration, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.IO.Files.SoArcConfiguration, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of SoArcConfiguration, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.IO.Files.SoArcConfiguration, To)()
  name.vb: MapEnums(Of SoArcConfiguration, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<SoArcConfiguration, To>
    nameWithType: EnumUtil.MapEnums<SoArcConfiguration, To>
    fullName: EnumUtil.MapEnums<SuperOffice.IO.Files.SoArcConfiguration, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of SoArcConfiguration, To)
    nameWithType: EnumUtil.MapEnums(Of SoArcConfiguration, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.IO.Files.SoArcConfiguration, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.Util.ObjectExtensions.AssignByReflection``1(SuperOffice.IO.Files.SoArcConfiguration)
  commentId: M:SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  parent: SuperOffice.Util.ObjectExtensions
  definition: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  name: AssignByReflection<SoArcConfiguration>(SoArcConfiguration)
  nameWithType: ObjectExtensions.AssignByReflection<SoArcConfiguration>(SoArcConfiguration)
  fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<SuperOffice.IO.Files.SoArcConfiguration>(SuperOffice.IO.Files.SoArcConfiguration)
  nameWithType.vb: ObjectExtensions.AssignByReflection(Of SoArcConfiguration)(SoArcConfiguration)
  fullName.vb: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of SuperOffice.IO.Files.SoArcConfiguration)(SuperOffice.IO.Files.SoArcConfiguration)
  name.vb: AssignByReflection(Of SoArcConfiguration)(SoArcConfiguration)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0)
    name: AssignByReflection<SoArcConfiguration>
    nameWithType: ObjectExtensions.AssignByReflection<SoArcConfiguration>
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<SuperOffice.IO.Files.SoArcConfiguration>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: SuperOffice.IO.Files.SoArcConfiguration
    name: SoArcConfiguration
    nameWithType: SoArcConfiguration
    fullName: SuperOffice.IO.Files.SoArcConfiguration
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0)
    name: AssignByReflection(Of SoArcConfiguration)
    nameWithType: ObjectExtensions.AssignByReflection(Of SoArcConfiguration)
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of SuperOffice.IO.Files.SoArcConfiguration)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: SuperOffice.IO.Files.SoArcConfiguration
    name: SoArcConfiguration
    nameWithType: SoArcConfiguration
    fullName: SuperOffice.IO.Files.SoArcConfiguration
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.Util.ObjectExtensions.GraphCopy``1
  commentId: M:SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  parent: SuperOffice.Util.ObjectExtensions
  definition: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  name: GraphCopy<SoArcConfiguration>()
  nameWithType: ObjectExtensions.GraphCopy<SoArcConfiguration>()
  fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<SuperOffice.IO.Files.SoArcConfiguration>()
  nameWithType.vb: ObjectExtensions.GraphCopy(Of SoArcConfiguration)()
  fullName.vb: SuperOffice.Util.ObjectExtensions.GraphCopy(Of SuperOffice.IO.Files.SoArcConfiguration)()
  name.vb: GraphCopy(Of SoArcConfiguration)()
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1
    name: GraphCopy<SoArcConfiguration>
    nameWithType: ObjectExtensions.GraphCopy<SoArcConfiguration>
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<SuperOffice.IO.Files.SoArcConfiguration>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1
    name: GraphCopy(Of SoArcConfiguration)
    nameWithType: ObjectExtensions.GraphCopy(Of SoArcConfiguration)
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy(Of SuperOffice.IO.Files.SoArcConfiguration)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.IO.Files.SoArcConfiguration.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<SoArcConfiguration, To>()
  nameWithType: Converters.MapEnums<SoArcConfiguration, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.IO.Files.SoArcConfiguration, To>()
  nameWithType.vb: Converters.MapEnums(Of SoArcConfiguration, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.IO.Files.SoArcConfiguration, To)()
  name.vb: MapEnums(Of SoArcConfiguration, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<SoArcConfiguration, To>
    nameWithType: Converters.MapEnums<SoArcConfiguration, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.IO.Files.SoArcConfiguration, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of SoArcConfiguration, To)
    nameWithType: Converters.MapEnums(Of SoArcConfiguration, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.IO.Files.SoArcConfiguration, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  commentId: M:SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
  isExternal: true
  name: AssignByReflection<T>(T, T)
  nameWithType: ObjectExtensions.AssignByReflection<T>(T, T)
  fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<T>(T, T)
  nameWithType.vb: ObjectExtensions.AssignByReflection(Of T)(T, T)
  fullName.vb: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of T)(T, T)
  name.vb: AssignByReflection(Of T)(T, T)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
    name: AssignByReflection<T>
    nameWithType: ObjectExtensions.AssignByReflection<T>
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.AssignByReflection``1(``0,``0)
    name: AssignByReflection(Of T)
    nameWithType: ObjectExtensions.AssignByReflection(Of T)
    fullName: SuperOffice.Util.ObjectExtensions.AssignByReflection(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.Util.ObjectExtensions
  commentId: T:SuperOffice.Util.ObjectExtensions
  parent: SuperOffice.Util
  isExternal: true
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: SuperOffice.Util.ObjectExtensions
- uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  commentId: M:SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
  isExternal: true
  name: GraphCopy<T>(T)
  nameWithType: ObjectExtensions.GraphCopy<T>(T)
  fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<T>(T)
  nameWithType.vb: ObjectExtensions.GraphCopy(Of T)(T)
  fullName.vb: SuperOffice.Util.ObjectExtensions.GraphCopy(Of T)(T)
  name.vb: GraphCopy(Of T)(T)
  spec.csharp:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
    name: GraphCopy<T>
    nameWithType: ObjectExtensions.GraphCopy<T>
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.Util.ObjectExtensions.GraphCopy``1(``0)
    name: GraphCopy(Of T)
    nameWithType: ObjectExtensions.GraphCopy(Of T)
    fullName: SuperOffice.Util.ObjectExtensions.GraphCopy(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.Util
  commentId: N:SuperOffice.Util
  isExternal: true
  name: SuperOffice.Util
  nameWithType: SuperOffice.Util
  fullName: SuperOffice.Util
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.IO.Files.SoArcConfiguration.#ctor*
  commentId: Overload:SuperOffice.IO.Files.SoArcConfiguration.#ctor
  isExternal: true
  name: SoArcConfiguration
  nameWithType: SoArcConfiguration.SoArcConfiguration
  fullName: SuperOffice.IO.Files.SoArcConfiguration.SoArcConfiguration
- uid: SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage*
  commentId: Overload:SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
  isExternal: true
  name: UseAzureBlobStorage
  nameWithType: SoArcConfiguration.UseAzureBlobStorage
  fullName: SuperOffice.IO.Files.SoArcConfiguration.UseAzureBlobStorage
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
