### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.ButtonBarConfigDialogDataHandler
  commentId: T:SuperOffice.CRM.ButtonBarConfigDialogDataHandler
  id: ButtonBarConfigDialogDataHandler
  parent: SuperOffice.CRM
  children: []
  langs:
  - csharp
  - vb
  name: ButtonBarConfigDialogDataHandler
  nameWithType: ButtonBarConfigDialogDataHandler
  fullName: SuperOffice.CRM.ButtonBarConfigDialogDataHandler
  type: Class
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM
  summary: "\nData fetch/save class for the Configuration dialog for the Button Bar. This is where the user configures which\nof the standard and user-defined tasks (visible in the popup menu of the Task button) should be visible as\nseparate buttons. The code in this class is also called from the <see cref=\"!:ConfigurationBuilder\"></see> in order to\ndetermine which of the user-defined tasks should also be buttonbar buttons.\n"
  syntax:
    content: 'public static class ButtonBarConfigDialogDataHandler : Object'
    content.vb: >-
      Public Module ButtonBarConfigDialogDataHandler

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
references:
- uid: SuperOffice.CRM
  commentId: N:SuperOffice.CRM
  isExternal: true
  name: SuperOffice.CRM
  nameWithType: SuperOffice.CRM
  fullName: SuperOffice.CRM
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
