### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.TimeZone
  commentId: T:SuperOffice.Configuration.ConfigFile.TimeZone
  id: ConfigFile.TimeZone
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
  langs:
  - csharp
  - vb
  name: ConfigFile.TimeZone
  nameWithType: ConfigFile.TimeZone
  fullName: SuperOffice.Configuration.ConfigFile.TimeZone
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to TimeZone.\n"
  syntax:
    content: 'public static class TimeZone : Object'
    content.vb: >-
      Public Module TimeZone

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
  commentId: P:SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
  id: ServiceUrl
  parent: SuperOffice.Configuration.ConfigFile.TimeZone
  langs:
  - csharp
  - vb
  name: ServiceUrl
  nameWithType: ConfigFile.TimeZone.ServiceUrl
  fullName: SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nURL for the TimeZone service\n"
  syntax:
    content: public static string ServiceUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ServiceUrl As String
  overload: SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
  isExternal: true
  name: ServiceUrl
  nameWithType: ConfigFile.TimeZone.ServiceUrl
  fullName: SuperOffice.Configuration.ConfigFile.TimeZone.ServiceUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
