### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  commentId: T:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  id: ConfigFile.GoogleRecaptcha
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
  - SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
  - SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
  langs:
  - csharp
  - vb
  name: ConfigFile.GoogleRecaptcha
  nameWithType: ConfigFile.GoogleRecaptcha
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfuguration values for the Google Recaptcha validation service.\n"
  syntax:
    content: 'public static class GoogleRecaptcha : Object'
    content.vb: >-
      Public Module GoogleRecaptcha

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
  commentId: P:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
  id: VerificationUrl
  parent: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  langs:
  - csharp
  - vb
  name: VerificationUrl
  nameWithType: ConfigFile.GoogleRecaptcha.VerificationUrl
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nURL for Google Recaptcha validation service.\n"
  syntax:
    content: public static string VerificationUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property VerificationUrl As String
  overload: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
  commentId: P:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
  id: SiteKey
  parent: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  langs:
  - csharp
  - vb
  name: SiteKey
  nameWithType: ConfigFile.GoogleRecaptcha.SiteKey
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe site key from from the Google Recaptcha instance.\n"
  syntax:
    content: public static string SiteKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property SiteKey As String
  overload: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
  commentId: P:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
  id: SecretKey
  parent: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha
  langs:
  - csharp
  - vb
  name: SecretKey
  nameWithType: ConfigFile.GoogleRecaptcha.SecretKey
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe secret key from the Google Recaptcha instance.\n"
  syntax:
    content: public static string SecretKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property SecretKey As String
  overload: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
  isExternal: true
  name: VerificationUrl
  nameWithType: ConfigFile.GoogleRecaptcha.VerificationUrl
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.VerificationUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
  isExternal: true
  name: SiteKey
  nameWithType: ConfigFile.GoogleRecaptcha.SiteKey
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SiteKey
- uid: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
  isExternal: true
  name: SecretKey
  nameWithType: ConfigFile.GoogleRecaptcha.SecretKey
  fullName: SuperOffice.Configuration.ConfigFile.GoogleRecaptcha.SecretKey
