### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  commentId: T:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  id: BulkUpdateSystem.FieldValueStorage
  parent: SuperOffice.CRM.BulkUpdate
  children:
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor(System.Boolean,System.String,System.String,System.String[])
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Active
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Key
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.OperationType
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Values
  langs:
  - csharp
  - vb
  name: BulkUpdateSystem.FieldValueStorage
  nameWithType: BulkUpdateSystem.FieldValueStorage
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  type: Class
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: 'protected class FieldValueStorage : Object'
    content.vb: >-
      Protected Class FieldValueStorage

          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.EnumUtil.MapEnums``2
  - SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - protected
  - class
  modifiers.vb:
  - Protected
  - Class
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Active
  commentId: F:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Active
  id: Active
  parent: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  langs:
  - csharp
  - vb
  name: Active
  nameWithType: BulkUpdateSystem.FieldValueStorage.Active
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Active
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: public bool Active
    return:
      type: System.Boolean
    content.vb: Public Active As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Key
  commentId: F:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Key
  id: Key
  parent: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: BulkUpdateSystem.FieldValueStorage.Key
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Key
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: public string Key
    return:
      type: System.String
    content.vb: Public Key As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.OperationType
  commentId: F:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.OperationType
  id: OperationType
  parent: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  langs:
  - csharp
  - vb
  name: OperationType
  nameWithType: BulkUpdateSystem.FieldValueStorage.OperationType
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.OperationType
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: public string OperationType
    return:
      type: System.String
    content.vb: Public OperationType As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Values
  commentId: F:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Values
  id: Values
  parent: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  langs:
  - csharp
  - vb
  name: Values
  nameWithType: BulkUpdateSystem.FieldValueStorage.Values
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.Values
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: public string[] Values
    return:
      type: System.String[]
    content.vb: Public Values As String()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor(System.Boolean,System.String,System.String,System.String[])
  commentId: M:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor(System.Boolean,System.String,System.String,System.String[])
  id: '#ctor(System.Boolean,System.String,System.String,System.String[])'
  parent: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage
  langs:
  - csharp
  - vb
  name: FieldValueStorage(Boolean, String, String, String[])
  nameWithType: BulkUpdateSystem.FieldValueStorage.FieldValueStorage(Boolean, String, String, String[])
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.FieldValueStorage(System.Boolean, System.String, System.String, System.String[])
  type: Constructor
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.BulkUpdate
  syntax:
    content: public FieldValueStorage(bool i_Active, string i_Key, string i_OperationType, string[] i_Values)
    parameters:
    - id: i_Active
      type: System.Boolean
    - id: i_Key
      type: System.String
    - id: i_OperationType
      type: System.String
    - id: i_Values
      type: System.String[]
    content.vb: Public Sub New(i_Active As Boolean, i_Key As String, i_OperationType As String, i_Values As String())
  overload: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor*
  nameWithType.vb: BulkUpdateSystem.FieldValueStorage.FieldValueStorage(Boolean, String, String, String())
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.FieldValueStorage(System.Boolean, System.String, System.String, System.String())
  name.vb: FieldValueStorage(Boolean, String, String, String())
references:
- uid: SuperOffice.CRM.BulkUpdate
  commentId: N:SuperOffice.CRM.BulkUpdate
  isExternal: true
  name: SuperOffice.CRM.BulkUpdate
  nameWithType: SuperOffice.CRM.BulkUpdate
  fullName: SuperOffice.CRM.BulkUpdate
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<BulkUpdateSystem.FieldValueStorage, To>()
  nameWithType: EnumUtil.MapEnums<BulkUpdateSystem.FieldValueStorage, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To)()
  name.vb: MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<BulkUpdateSystem.FieldValueStorage, To>
    nameWithType: EnumUtil.MapEnums<BulkUpdateSystem.FieldValueStorage, To>
    fullName: EnumUtil.MapEnums<SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)
    nameWithType: EnumUtil.MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<BulkUpdateSystem.FieldValueStorage, To>()
  nameWithType: Converters.MapEnums<BulkUpdateSystem.FieldValueStorage, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To>()
  nameWithType.vb: Converters.MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To)()
  name.vb: MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<BulkUpdateSystem.FieldValueStorage, To>
    nameWithType: Converters.MapEnums<BulkUpdateSystem.FieldValueStorage, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)
    nameWithType: Converters.MapEnums(Of BulkUpdateSystem.FieldValueStorage, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String[]
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor*
  commentId: Overload:SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.#ctor
  isExternal: true
  name: FieldValueStorage
  nameWithType: BulkUpdateSystem.FieldValueStorage.FieldValueStorage
  fullName: SuperOffice.CRM.BulkUpdate.BulkUpdateSystem.FieldValueStorage.FieldValueStorage
