### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Pocket
  commentId: T:SuperOffice.Configuration.ConfigFile.Pocket
  id: ConfigFile.Pocket
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
  - SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
  langs:
  - csharp
  - vb
  name: ConfigFile.Pocket
  nameWithType: ConfigFile.Pocket
  fullName: SuperOffice.Configuration.ConfigFile.Pocket
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values for Pocket specific features\n"
  syntax:
    content: 'public static class Pocket : Object'
    content.vb: >-
      Public Module Pocket

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
  commentId: P:SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
  id: AzureNotificationHubConnectionString
  parent: SuperOffice.Configuration.ConfigFile.Pocket
  langs:
  - csharp
  - vb
  name: AzureNotificationHubConnectionString
  nameWithType: ConfigFile.Pocket.AzureNotificationHubConnectionString
  fullName: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConnection string from Azure notification hub access policies\n"
  syntax:
    content: public static string AzureNotificationHubConnectionString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property AzureNotificationHubConnectionString As String
  overload: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
  commentId: P:SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
  id: AzureNotificationHubName
  parent: SuperOffice.Configuration.ConfigFile.Pocket
  langs:
  - csharp
  - vb
  name: AzureNotificationHubName
  nameWithType: ConfigFile.Pocket.AzureNotificationHubName
  fullName: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe name of the Azure notification hub\n"
  syntax:
    content: public static string AzureNotificationHubName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property AzureNotificationHubName As String
  overload: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
  isExternal: true
  name: AzureNotificationHubConnectionString
  nameWithType: ConfigFile.Pocket.AzureNotificationHubConnectionString
  fullName: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubConnectionString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
  isExternal: true
  name: AzureNotificationHubName
  nameWithType: ConfigFile.Pocket.AzureNotificationHubName
  fullName: SuperOffice.Configuration.ConfigFile.Pocket.AzureNotificationHubName
