### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Sync
  commentId: T:SuperOffice.Configuration.ConfigFile.Sync
  id: ConfigFile.Sync
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
  - SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
  langs:
  - csharp
  - vb
  name: ConfigFile.Sync
  nameWithType: ConfigFile.Sync
  fullName: SuperOffice.Configuration.ConfigFile.Sync
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to SuperOffice Sync (i.e. qSoSync).\n"
  syntax:
    content: 'public static class Sync : Object'
    content.vb: >-
      Public Module Sync

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
  commentId: P:SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
  id: SettingsSlidingExpiration
  parent: SuperOffice.Configuration.ConfigFile.Sync
  langs:
  - csharp
  - vb
  name: SettingsSlidingExpiration
  nameWithType: ConfigFile.Sync.SettingsSlidingExpiration
  fullName: SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nSettings related to synchronization are configured using the SoSyncAdmin client, stored in the SuperOffice database and internally in SoSync held in a cache.  This cache has two time-out values.  One of the values are related to the absolute expiry time after the value is inserted in the cache and the second relates to the expiry time since the value was last used.  This configuration value address the latter and refers to time since last used.  300 seconds is default value.\n"
  syntax:
    content: public static int SettingsSlidingExpiration { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property SettingsSlidingExpiration As Integer
  overload: SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
  commentId: P:SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
  id: SettingsAbsoluteExpiration
  parent: SuperOffice.Configuration.ConfigFile.Sync
  langs:
  - csharp
  - vb
  name: SettingsAbsoluteExpiration
  nameWithType: ConfigFile.Sync.SettingsAbsoluteExpiration
  fullName: SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nSettings related to synchronization are configured using the SoSyncAdmin client, stored in the SuperOffice database and internally in SoSync held in a cache.  This cache has two time-out values.  One of the values are related to the absolute expiry time after the value is inserted in the cache and the second relates to the expiry time since the value was last used.  This configuration value address the first related to time since read from the database.  900 seconds is default value.\n"
  syntax:
    content: public static int SettingsAbsoluteExpiration { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property SettingsAbsoluteExpiration As Integer
  overload: SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
  isExternal: true
  name: SettingsSlidingExpiration
  nameWithType: ConfigFile.Sync.SettingsSlidingExpiration
  fullName: SuperOffice.Configuration.ConfigFile.Sync.SettingsSlidingExpiration
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
  isExternal: true
  name: SettingsAbsoluteExpiration
  nameWithType: ConfigFile.Sync.SettingsAbsoluteExpiration
  fullName: SuperOffice.Configuration.ConfigFile.Sync.SettingsAbsoluteExpiration
