### YamlMime:ManagedReference
items:
- uid: SuperOffice.UI.Configuration.Layout
  commentId: T:SuperOffice.UI.Configuration.Layout
  id: Layout
  parent: SuperOffice.UI.Configuration
  children:
  - SuperOffice.UI.Configuration.Layout.Absolute
  - SuperOffice.UI.Configuration.Layout.Flow
  - SuperOffice.UI.Configuration.Layout.Grid
  - SuperOffice.UI.Configuration.Layout.value__
  langs:
  - csharp
  - vb
  name: Layout
  nameWithType: Layout
  fullName: SuperOffice.UI.Configuration.Layout
  type: Class
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\n<strong>Warning: Preliminary, informal code; subject to change!</strong><p></p>Layout type for control containers\n"
  syntax:
    content: 'public sealed class Layout : Enum'
    content.vb: >-
      Public NotInheritable Class Layout

          Inherits



           Enum
  inheritance:
  - System.Object
  extensionMethods:
  - SuperOffice.UI.Configuration.Layout.EnumUtil.MapEnums``2
  - SuperOffice.UI.Configuration.Layout.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: SuperOffice.UI.Configuration.Layout.value__
  commentId: F:SuperOffice.UI.Configuration.Layout.value__
  id: value__
  parent: SuperOffice.UI.Configuration.Layout
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: Layout.value__
  fullName: SuperOffice.UI.Configuration.Layout.value__
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.UI.Configuration.Layout.Flow
  commentId: F:SuperOffice.UI.Configuration.Layout.Flow
  id: Flow
  parent: SuperOffice.UI.Configuration.Layout
  langs:
  - csharp
  - vb
  name: Flow
  nameWithType: Layout.Flow
  fullName: SuperOffice.UI.Configuration.Layout.Flow
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe controls in the container should have a Flow layout, one after another\n"
  syntax:
    content: public const Layout Flow
    return:
      type: SuperOffice.UI.Configuration.Layout
    content.vb: Public Const Flow As Layout
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.UI.Configuration.Layout.Grid
  commentId: F:SuperOffice.UI.Configuration.Layout.Grid
  id: Grid
  parent: SuperOffice.UI.Configuration.Layout
  langs:
  - csharp
  - vb
  name: Grid
  nameWithType: Layout.Grid
  fullName: SuperOffice.UI.Configuration.Layout.Grid
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe controls in the container should have a Grid layout, with a specified number of columns and rows\n"
  syntax:
    content: public const Layout Grid
    return:
      type: SuperOffice.UI.Configuration.Layout
    content.vb: Public Const Grid As Layout
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.UI.Configuration.Layout.Absolute
  commentId: F:SuperOffice.UI.Configuration.Layout.Absolute
  id: Absolute
  parent: SuperOffice.UI.Configuration.Layout
  langs:
  - csharp
  - vb
  name: Absolute
  nameWithType: Layout.Absolute
  fullName: SuperOffice.UI.Configuration.Layout.Absolute
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe controls in the container should be positioned with absolute coordinates for each control\n"
  syntax:
    content: public const Layout Absolute
    return:
      type: SuperOffice.UI.Configuration.Layout
    content.vb: Public Const Absolute As Layout
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.UI.Configuration
  commentId: N:SuperOffice.UI.Configuration
  isExternal: true
  name: SuperOffice.UI.Configuration
  nameWithType: SuperOffice.UI.Configuration
  fullName: SuperOffice.UI.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.UI.Configuration.Layout.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<Layout, To>()
  nameWithType: EnumUtil.MapEnums<Layout, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.UI.Configuration.Layout, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of Layout, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.UI.Configuration.Layout, To)()
  name.vb: MapEnums(Of Layout, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<Layout, To>
    nameWithType: EnumUtil.MapEnums<Layout, To>
    fullName: EnumUtil.MapEnums<SuperOffice.UI.Configuration.Layout, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of Layout, To)
    nameWithType: EnumUtil.MapEnums(Of Layout, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.UI.Configuration.Layout, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.UI.Configuration.Layout.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<Layout, To>()
  nameWithType: Converters.MapEnums<Layout, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.UI.Configuration.Layout, To>()
  nameWithType.vb: Converters.MapEnums(Of Layout, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.UI.Configuration.Layout, To)()
  name.vb: MapEnums(Of Layout, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<Layout, To>
    nameWithType: Converters.MapEnums<Layout, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.UI.Configuration.Layout, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of Layout, To)
    nameWithType: Converters.MapEnums(Of Layout, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.UI.Configuration.Layout, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.UI.Configuration.Layout
  commentId: T:SuperOffice.UI.Configuration.Layout
  parent: SuperOffice.UI.Configuration
  isExternal: true
  name: Layout
  nameWithType: Layout
  fullName: SuperOffice.UI.Configuration.Layout
