### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  commentId: T:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  id: Constants.RestrictionValues
  parent: SuperOffice.CRM.ArchiveLists
  children:
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.HintDelimiter
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.R
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.RPLUS
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.TypeDelimiter
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.W
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WDT
  - SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WPLUS
  langs:
  - csharp
  - vb
  name: Constants.RestrictionValues
  nameWithType: Constants.RestrictionValues
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: 'public static class RestrictionValues : Object'
    content.vb: >-
      Public Module RestrictionValues

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.HintDelimiter
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.HintDelimiter
  id: HintDelimiter
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: HintDelimiter
  nameWithType: Constants.RestrictionValues.HintDelimiter
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.HintDelimiter
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string HintDelimiter = ";"
    return:
      type: System.String
    content.vb: Public Const HintDelimiter As String = ";"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.TypeDelimiter
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.TypeDelimiter
  id: TypeDelimiter
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: TypeDelimiter
  nameWithType: Constants.RestrictionValues.TypeDelimiter
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.TypeDelimiter
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string TypeDelimiter = ":"
    return:
      type: System.String
    content.vb: Public Const TypeDelimiter As String = ":"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.R
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.R
  id: R
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: R
  nameWithType: Constants.RestrictionValues.R
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.R
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string R = "R"
    return:
      type: System.String
    content.vb: Public Const R As String = "R"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.W
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.W
  id: W
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: W
  nameWithType: Constants.RestrictionValues.W
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.W
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string W = "W"
    return:
      type: System.String
    content.vb: Public Const W As String = "W"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WDT
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WDT
  id: WDT
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: WDT
  nameWithType: Constants.RestrictionValues.WDT
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WDT
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string WDT = "WDT"
    return:
      type: System.String
    content.vb: Public Const WDT As String = "WDT"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WPLUS
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WPLUS
  id: WPLUS
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: WPLUS
  nameWithType: Constants.RestrictionValues.WPLUS
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.WPLUS
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string WPLUS = "W+"
    return:
      type: System.String
    content.vb: Public Const WPLUS As String = "W+"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.RPLUS
  commentId: F:SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.RPLUS
  id: RPLUS
  parent: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues
  langs:
  - csharp
  - vb
  name: RPLUS
  nameWithType: Constants.RestrictionValues.RPLUS
  fullName: SuperOffice.CRM.ArchiveLists.Constants.RestrictionValues.RPLUS
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.CRM.ArchiveLists
  syntax:
    content: public const string RPLUS = "R+"
    return:
      type: System.String
    content.vb: Public Const RPLUS As String = "R+"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.CRM.ArchiveLists
  commentId: N:SuperOffice.CRM.ArchiveLists
  isExternal: true
  name: SuperOffice.CRM.ArchiveLists
  nameWithType: SuperOffice.CRM.ArchiveLists
  fullName: SuperOffice.CRM.ArchiveLists
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
