### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Data.Session
  commentId: T:SuperOffice.Configuration.ConfigFile.Data.Session
  id: ConfigFile.Data.Session
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
  langs:
  - csharp
  - vb
  name: ConfigFile.Data.Session
  nameWithType: ConfigFile.Data.Session
  fullName: SuperOffice.Configuration.ConfigFile.Data.Session
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThis section governs session handling - what is the scope/storage of the session state, etc\n"
  syntax:
    content: 'public static class Session : Object'
    content.vb: >-
      Public Module Session

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
  commentId: P:SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
  id: ReauthenticateOnDeserialization
  parent: SuperOffice.Configuration.ConfigFile.Data.Session
  langs:
  - csharp
  - vb
  name: ReauthenticateOnDeserialization
  nameWithType: ConfigFile.Data.Session.ReauthenticateOnDeserialization
  fullName: SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nA full re-authentication is carried out each time the session is de-serialized (e.g. from the session server).\n"
  syntax:
    content: public static bool ReauthenticateOnDeserialization { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property ReauthenticateOnDeserialization As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
  isExternal: true
  name: ReauthenticateOnDeserialization
  nameWithType: ConfigFile.Data.Session.ReauthenticateOnDeserialization
  fullName: SuperOffice.Configuration.ConfigFile.Data.Session.ReauthenticateOnDeserialization
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
