### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication
  commentId: T:SuperOffice.Configuration.ConfigFile.SoFormsAuthentication
  id: ConfigFile.SoFormsAuthentication
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
  - SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
  langs:
  - csharp
  - vb
  name: ConfigFile.SoFormsAuthentication
  nameWithType: ConfigFile.SoFormsAuthentication
  fullName: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUtility class used to access the SoFormsAuthentication section in the config file.\n"
  syntax:
    content: 'public static class SoFormsAuthentication : Object'
    content.vb: >-
      Public Module SoFormsAuthentication

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
  commentId: P:SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
  id: IgnoreList
  parent: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication
  langs:
  - csharp
  - vb
  name: IgnoreList
  nameWithType: ConfigFile.SoFormsAuthentication.IgnoreList
  fullName: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nList of pages and folders the SoFormsAuthentication should ignore.\n"
  syntax:
    content: public static List<string> IgnoreList { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Shared ReadOnly Property IgnoreList As List(Of String)
  overload: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
  commentId: P:SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
  id: Pages
  parent: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication
  langs:
  - csharp
  - vb
  name: Pages
  nameWithType: ConfigFile.SoFormsAuthentication.Pages
  fullName: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nList of pages. Should contain a dictionaty with the following keys; LoginUrl and DefaultUrl, and optional LogoutUrl and PocketCrmLoginPage\n"
  syntax:
    content: public static Dictionary<string, string> Pages { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.String}
    content.vb: Public Shared ReadOnly Property Pages As Dictionary(Of String, String)
  overload: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
  isExternal: true
  name: IgnoreList
  nameWithType: ConfigFile.SoFormsAuthentication.IgnoreList
  fullName: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.IgnoreList
- uid: System.Collections.Generic.List{System.String}
  commentId: '!:System.Collections.Generic.List{System.String}'
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: System.Collections.Generic.List<>
  nameWithType.vb: List(Of )
  fullName.vb: System.Collections.Generic.List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
  isExternal: true
  name: Pages
  nameWithType: ConfigFile.SoFormsAuthentication.Pages
  fullName: SuperOffice.Configuration.ConfigFile.SoFormsAuthentication.Pages
- uid: System.Collections.Generic.Dictionary{System.String,System.String}
  commentId: '!:System.Collections.Generic.Dictionary{System.String,System.String}'
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<String, String>
  nameWithType: Dictionary<String, String>
  fullName: System.Collections.Generic.Dictionary<System.String, System.String>
  nameWithType.vb: Dictionary(Of String, String)
  fullName.vb: System.Collections.Generic.Dictionary(Of System.String, System.String)
  name.vb: Dictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.Dictionary`2
  isExternal: true
  name: Dictionary<, >
  nameWithType: Dictionary<, >
  fullName: System.Collections.Generic.Dictionary<, >
  nameWithType.vb: Dictionary(Of , )
  fullName.vb: System.Collections.Generic.Dictionary(Of , )
  name.vb: Dictionary(Of , )
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
