### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy
  commentId: T:SuperOffice.Configuration.ConfigFile.CustomProxy
  id: ConfigFile.CustomProxy
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
  - SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
  - SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
  - SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  - SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  - SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  langs:
  - csharp
  - vb
  name: ConfigFile.CustomProxy
  nameWithType: ConfigFile.CustomProxy
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values for using Custom Proxy for communication with Internet\n"
  syntax:
    content: 'public static class CustomProxy : Object'
    content.vb: >-
      Public Module CustomProxy

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  id: UseCustomProxyForPublicAccess
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: UseCustomProxyForPublicAccess
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUse Custom Proxy server, even for local addresses, when communicating to public internet services. This value overrides machine and other config default settings for proxy server.\n"
  syntax:
    content: public static bool UseCustomProxyForPublicAccess { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property UseCustomProxyForPublicAccess As Boolean
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  id: UseCustomProxyForIntegrationServer
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: UseCustomProxyForIntegrationServer
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUse Custom Proxy server, even for local addresses, when communicating to ErpSync and Remote (Online) Quote Connector. This value overrides machine and other config default settings for proxy server.\n"
  syntax:
    content: public static bool UseCustomProxyForIntegrationServer { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property UseCustomProxyForIntegrationServer As Boolean
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  id: UseCustomProxyForWebhooks
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: UseCustomProxyForWebhooks
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUse Custom Proxy server when posting to webhook URLs. Uses the SSL port. This value overrides machine and other config default settings for proxy server.\n"
  syntax:
    content: public static bool UseCustomProxyForWebhooks { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property UseCustomProxyForWebhooks As Boolean
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
  id: CustomProxyHost
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: CustomProxyHost
  nameWithType: ConfigFile.CustomProxy.CustomProxyHost
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nHost for custom proxy used when UseCustomProxyForPublicAccess or UseCustomProxyForIntegrationServer is set to true\n"
  syntax:
    content: public static string CustomProxyHost { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CustomProxyHost As String
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
  id: CustomProxyPort
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: CustomProxyPort
  nameWithType: ConfigFile.CustomProxy.CustomProxyPort
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nPort for custom proxy used when UseCustomProxyForPublicAccess or UseCustomProxyForIntegrationServer is set to true\n"
  syntax:
    content: public static string CustomProxyPort { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CustomProxyPort As String
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
  id: CustomProxySslPort
  parent: SuperOffice.Configuration.ConfigFile.CustomProxy
  langs:
  - csharp
  - vb
  name: CustomProxySslPort
  nameWithType: ConfigFile.CustomProxy.CustomProxySslPort
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nSSL Port for custom proxy used when UseCustomProxyForWebhooks is set to true\n"
  syntax:
    content: public static string CustomProxySslPort { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CustomProxySslPort As String
  overload: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  isExternal: true
  name: UseCustomProxyForPublicAccess
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForPublicAccess
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  isExternal: true
  name: UseCustomProxyForIntegrationServer
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForIntegrationServer
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  isExternal: true
  name: UseCustomProxyForWebhooks
  nameWithType: ConfigFile.CustomProxy.UseCustomProxyForWebhooks
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.UseCustomProxyForWebhooks
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
  isExternal: true
  name: CustomProxyHost
  nameWithType: ConfigFile.CustomProxy.CustomProxyHost
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyHost
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
  isExternal: true
  name: CustomProxyPort
  nameWithType: ConfigFile.CustomProxy.CustomProxyPort
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxyPort
- uid: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
  isExternal: true
  name: CustomProxySslPort
  nameWithType: ConfigFile.CustomProxy.CustomProxySslPort
  fullName: SuperOffice.Configuration.ConfigFile.CustomProxy.CustomProxySslPort
