### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  commentId: T:SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  id: DBC.ErpConfigurationFields
  parent: SuperOffice.CRM.Data
  children:
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ConnectionRank
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ErpConfigurationId
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Registered
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.RegisteredAssociateId
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncInterval
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncRunning
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Updated
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedAssociateId
  - SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedCount
  langs:
  - csharp
  - vb
  name: DBC.ErpConfigurationFields
  nameWithType: DBC.ErpConfigurationFields
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  type: Class
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nFields for ErpConfiguration, Global settings for the Erp Integration Server\n"
  syntax:
    content: 'public static class ErpConfigurationFields : Object'
    content.vb: >-
      Public Module ErpConfigurationFields

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ErpConfigurationId
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ErpConfigurationId
  id: ErpConfigurationId
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: ErpConfigurationId
  nameWithType: DBC.ErpConfigurationFields.ErpConfigurationId
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ErpConfigurationId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.ErpConfigurationId: Primary key\n"
  syntax:
    content: public const string ErpConfigurationId = "erpconfiguration_id"
    return:
      type: System.String
    content.vb: Public Const ErpConfigurationId As String = "erpconfiguration_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ConnectionRank
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ConnectionRank
  id: ConnectionRank
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: ConnectionRank
  nameWithType: DBC.ErpConfigurationFields.ConnectionRank
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.ConnectionRank
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.ConnectionRank: Semicolon-separated primary keys of ErpConnection records, with &apos;0&apos; representing the SuperOffice &apos;connector&apos;, giving the replication order\n"
  syntax:
    content: public const string ConnectionRank = "ConnectionRank"
    return:
      type: System.String
    content.vb: Public Const ConnectionRank As String = "ConnectionRank"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncInterval
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncInterval
  id: SyncInterval
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: SyncInterval
  nameWithType: DBC.ErpConfigurationFields.SyncInterval
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncInterval
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.SyncInterval: Interval between successive pollings for changes, in seconds\n"
  syntax:
    content: public const string SyncInterval = "SyncInterval"
    return:
      type: System.String
    content.vb: Public Const SyncInterval As String = "SyncInterval"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncRunning
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncRunning
  id: SyncRunning
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: SyncRunning
  nameWithType: DBC.ErpConfigurationFields.SyncRunning
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.SyncRunning
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.SyncRunning: Is the sync currently running or not; reflects state of [On] [Off] buttons in the Admin GUI\n"
  syntax:
    content: public const string SyncRunning = "SyncRunning"
    return:
      type: System.String
    content.vb: Public Const SyncRunning As String = "SyncRunning"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Registered
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Registered
  id: Registered
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: Registered
  nameWithType: DBC.ErpConfigurationFields.Registered
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Registered
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.Registered: Registered when\n"
  syntax:
    content: public const string Registered = "registered"
    return:
      type: System.String
    content.vb: Public Const Registered As String = "registered"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.RegisteredAssociateId
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.RegisteredAssociateId
  id: RegisteredAssociateId
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: RegisteredAssociateId
  nameWithType: DBC.ErpConfigurationFields.RegisteredAssociateId
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.RegisteredAssociateId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.RegisteredAssociateId: Registered by whom\n"
  syntax:
    content: public const string RegisteredAssociateId = "registered_associate_id"
    return:
      type: System.String
    content.vb: Public Const RegisteredAssociateId As String = "registered_associate_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Updated
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Updated
  id: Updated
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: Updated
  nameWithType: DBC.ErpConfigurationFields.Updated
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.Updated
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.Updated: Last updated when\n"
  syntax:
    content: public const string Updated = "updated"
    return:
      type: System.String
    content.vb: Public Const Updated As String = "updated"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedAssociateId
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedAssociateId
  id: UpdatedAssociateId
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: UpdatedAssociateId
  nameWithType: DBC.ErpConfigurationFields.UpdatedAssociateId
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedAssociateId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.UpdatedAssociateId: Last updated by whom\n"
  syntax:
    content: public const string UpdatedAssociateId = "updated_associate_id"
    return:
      type: System.String
    content.vb: Public Const UpdatedAssociateId As String = "updated_associate_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedCount
  commentId: F:SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedCount
  id: UpdatedCount
  parent: SuperOffice.CRM.Data.DBC.ErpConfigurationFields
  langs:
  - csharp
  - vb
  name: UpdatedCount
  nameWithType: DBC.ErpConfigurationFields.UpdatedCount
  fullName: SuperOffice.CRM.Data.DBC.ErpConfigurationFields.UpdatedCount
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nErpConfiguration.UpdatedCount: Number of updates made to this record\n"
  syntax:
    content: public const string UpdatedCount = "updatedCount"
    return:
      type: System.String
    content.vb: Public Const UpdatedCount As String = "updatedCount"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.CRM.Data
  commentId: N:SuperOffice.CRM.Data
  isExternal: true
  name: SuperOffice.CRM.Data
  nameWithType: SuperOffice.CRM.Data
  fullName: SuperOffice.CRM.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
