### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.AccessGateway
  commentId: T:SuperOffice.Configuration.ConfigFile.AccessGateway
  id: ConfigFile.AccessGateway
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
  langs:
  - csharp
  - vb
  name: ConfigFile.AccessGateway
  nameWithType: ConfigFile.AccessGateway
  fullName: SuperOffice.Configuration.ConfigFile.AccessGateway
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to Access Gateway.\n"
  syntax:
    content: 'public static class AccessGateway : Object'
    content.vb: >-
      Public Module AccessGateway

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
  commentId: P:SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
  id: BaseUrl
  parent: SuperOffice.Configuration.ConfigFile.AccessGateway
  langs:
  - csharp
  - vb
  name: BaseUrl
  nameWithType: ConfigFile.AccessGateway.BaseUrl
  fullName: SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nBase URL to Access Gateway\n"
  syntax:
    content: public static string BaseUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property BaseUrl As String
  overload: SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
  isExternal: true
  name: BaseUrl
  nameWithType: ConfigFile.AccessGateway.BaseUrl
  fullName: SuperOffice.Configuration.ConfigFile.AccessGateway.BaseUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
