### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Downloads
  commentId: T:SuperOffice.Configuration.ConfigFile.Downloads
  id: ConfigFile.Downloads
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
  - SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
  langs:
  - csharp
  - vb
  name: ConfigFile.Downloads
  nameWithType: ConfigFile.Downloads
  fullName: SuperOffice.Configuration.ConfigFile.Downloads
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to Downloads.\n"
  syntax:
    content: 'public static class Downloads : Object'
    content.vb: >-
      Public Module Downloads

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
  commentId: P:SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
  id: WebToolVersion
  parent: SuperOffice.Configuration.ConfigFile.Downloads
  langs:
  - csharp
  - vb
  name: WebToolVersion
  nameWithType: ConfigFile.Downloads.WebToolVersion
  fullName: SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe version number to use for upgrade check.\n"
  syntax:
    content: public static string WebToolVersion { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property WebToolVersion As String
  overload: SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
  commentId: P:SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
  id: ReportingInterval
  parent: SuperOffice.Configuration.ConfigFile.Downloads
  langs:
  - csharp
  - vb
  name: ReportingInterval
  nameWithType: ConfigFile.Downloads.ReportingInterval
  fullName: SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe interval (in seconds) which the web-installation will require activity udpates from WebTools-clients in order for the clients to be considered active.\n"
  syntax:
    content: public static int ReportingInterval { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property ReportingInterval As Integer
  overload: SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
  isExternal: true
  name: WebToolVersion
  nameWithType: ConfigFile.Downloads.WebToolVersion
  fullName: SuperOffice.Configuration.ConfigFile.Downloads.WebToolVersion
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
  isExternal: true
  name: ReportingInterval
  nameWithType: ConfigFile.Downloads.ReportingInterval
  fullName: SuperOffice.Configuration.ConfigFile.Downloads.ReportingInterval
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
