### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.SuperId
  commentId: T:SuperOffice.Configuration.ConfigFile.SuperId
  id: ConfigFile.SuperId
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.SuperId.Environment
  - SuperOffice.Configuration.ConfigFile.SuperId.TenantId
  - SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
  - SuperOffice.Configuration.ConfigFile.SuperId.Url
  langs:
  - csharp
  - vb
  name: ConfigFile.SuperId
  nameWithType: ConfigFile.SuperId
  fullName: SuperOffice.Configuration.ConfigFile.SuperId
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values for accessing SuperId\n"
  syntax:
    content: 'public static class SuperId : Object'
    content.vb: >-
      Public Module SuperId

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.SuperId.Url
  commentId: P:SuperOffice.Configuration.ConfigFile.SuperId.Url
  id: Url
  parent: SuperOffice.Configuration.ConfigFile.SuperId
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: ConfigFile.SuperId.Url
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.Url
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUrl to SuperId\n"
  syntax:
    content: public static string Url { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property Url As String
  overload: SuperOffice.Configuration.ConfigFile.SuperId.Url*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
  commentId: P:SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
  id: TenantKey
  parent: SuperOffice.Configuration.ConfigFile.SuperId
  langs:
  - csharp
  - vb
  name: TenantKey
  nameWithType: ConfigFile.SuperId.TenantKey
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nA shared secret between SuperId and netserver\n"
  syntax:
    content: public static string TenantKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property TenantKey As String
  overload: SuperOffice.Configuration.ConfigFile.SuperId.TenantKey*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.SuperId.TenantId
  commentId: P:SuperOffice.Configuration.ConfigFile.SuperId.TenantId
  id: TenantId
  parent: SuperOffice.Configuration.ConfigFile.SuperId
  langs:
  - csharp
  - vb
  name: TenantId
  nameWithType: ConfigFile.SuperId.TenantId
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.TenantId
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nTenantId in SuperId\n"
  syntax:
    content: public static int TenantId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property TenantId As Integer
  overload: SuperOffice.Configuration.ConfigFile.SuperId.TenantId*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.SuperId.Environment
  commentId: P:SuperOffice.Configuration.ConfigFile.SuperId.Environment
  id: Environment
  parent: SuperOffice.Configuration.ConfigFile.SuperId
  langs:
  - csharp
  - vb
  name: Environment
  nameWithType: ConfigFile.SuperId.Environment
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.Environment
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nEnvironment in SuperId\n"
  syntax:
    content: public static string Environment { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property Environment As String
  overload: SuperOffice.Configuration.ConfigFile.SuperId.Environment*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.SuperId.Url*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuperId.Url
  isExternal: true
  name: Url
  nameWithType: ConfigFile.SuperId.Url
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.Url
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.SuperId.TenantKey*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
  isExternal: true
  name: TenantKey
  nameWithType: ConfigFile.SuperId.TenantKey
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.TenantKey
- uid: SuperOffice.Configuration.ConfigFile.SuperId.TenantId*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuperId.TenantId
  isExternal: true
  name: TenantId
  nameWithType: ConfigFile.SuperId.TenantId
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.TenantId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.Configuration.ConfigFile.SuperId.Environment*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.SuperId.Environment
  isExternal: true
  name: Environment
  nameWithType: ConfigFile.SuperId.Environment
  fullName: SuperOffice.Configuration.ConfigFile.SuperId.Environment
