### YamlMime:ManagedReference
items:
- uid: SuperOffice.UI.Configuration.Constants
  commentId: T:SuperOffice.UI.Configuration.Constants
  id: Constants
  parent: SuperOffice.UI.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: Constants
  nameWithType: Constants
  fullName: SuperOffice.UI.Configuration.Constants
  type: Class
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nConstants related to custom UI\n"
  syntax:
    content: 'public static class Constants : Object'
    content.vb: >-
      Public Module Constants

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
references:
- uid: SuperOffice.UI.Configuration
  commentId: N:SuperOffice.UI.Configuration
  isExternal: true
  name: SuperOffice.UI.Configuration
  nameWithType: SuperOffice.UI.Configuration
  fullName: SuperOffice.UI.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
