### YamlMime:ManagedReference
items:
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  commentId: T:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  id: ConfigurationAttributes.ControlElements
  parent: SuperOffice.DCF.Configuration
  children:
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Binding
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Caption
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Control
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Data
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Datasource
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Tooltip
  langs:
  - csharp
  - vb
  name: ConfigurationAttributes.ControlElements
  nameWithType: ConfigurationAttributes.ControlElements
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class ControlElements : Object'
    content.vb: >-
      Public Module ControlElements

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Caption
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Caption
  id: Caption
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Caption
  nameWithType: ConfigurationAttributes.ControlElements.Caption
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Caption
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Caption = "caption"
    return:
      type: System.String
    content.vb: Public Const Caption As String = "caption"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Tooltip
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Tooltip
  id: Tooltip
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Tooltip
  nameWithType: ConfigurationAttributes.ControlElements.Tooltip
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Tooltip
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Tooltip = "tooltip"
    return:
      type: System.String
    content.vb: Public Const Tooltip As String = "tooltip"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Datasource
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Datasource
  id: Datasource
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Datasource
  nameWithType: ConfigurationAttributes.ControlElements.Datasource
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Datasource
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Datasource = "datasource"
    return:
      type: System.String
    content.vb: Public Const Datasource As String = "datasource"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Control
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Control
  id: Control
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Control
  nameWithType: ConfigurationAttributes.ControlElements.Control
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Control
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Control = "control"
    return:
      type: System.String
    content.vb: Public Const Control As String = "control"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Binding
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Binding
  id: Binding
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: ConfigurationAttributes.ControlElements.Binding
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Binding
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Binding = "binding"
    return:
      type: System.String
    content.vb: Public Const Binding As String = "binding"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Data
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Data
  id: Data
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements
  langs:
  - csharp
  - vb
  name: Data
  nameWithType: ConfigurationAttributes.ControlElements.Data
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Data
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Data = "data"
    return:
      type: System.String
    content.vb: Public Const Data As String = "data"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.DCF.Configuration
  commentId: N:SuperOffice.DCF.Configuration
  isExternal: true
  name: SuperOffice.DCF.Configuration
  nameWithType: SuperOffice.DCF.Configuration
  fullName: SuperOffice.DCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
