### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  commentId: T:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  id: ConfigFile.ClientConfigurationProvider
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
  - SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  - SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
  - SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
  - SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  langs:
  - csharp
  - vb
  name: ConfigFile.ClientConfigurationProvider
  nameWithType: ConfigFile.ClientConfigurationProvider
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration for the Web Client configuration data provider\n"
  syntax:
    content: 'public static class ClientConfigurationProvider : Object'
    content.vb: >-
      Public Module ClientConfigurationProvider

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
  commentId: P:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
  id: FilePath
  parent: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  langs:
  - csharp
  - vb
  name: FilePath
  nameWithType: ConfigFile.ClientConfigurationProvider.FilePath
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nFile path for standard .config files\n"
  syntax:
    content: public static string FilePath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property FilePath As String
  overload: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
  commentId: P:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
  id: CacheConfigurations
  parent: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  langs:
  - csharp
  - vb
  name: CacheConfigurations
  nameWithType: ConfigFile.ClientConfigurationProvider.CacheConfigurations
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nShould GUI config data be cached?\n"
  syntax:
    content: public static bool CacheConfigurations { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property CacheConfigurations As Boolean
  overload: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  commentId: P:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  id: CacheUserPreferences
  parent: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  langs:
  - csharp
  - vb
  name: CacheUserPreferences
  nameWithType: ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nShould GUI config data be cached?\n"
  syntax:
    content: public static bool CacheUserPreferences { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property CacheUserPreferences As Boolean
  overload: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  commentId: P:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  id: ValidateConfigurations
  parent: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  langs:
  - csharp
  - vb
  name: ValidateConfigurations
  nameWithType: ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nShould GUI config data be validated runtime?\n"
  syntax:
    content: public static bool ValidateConfigurations { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property ValidateConfigurations As Boolean
  overload: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
  commentId: P:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
  id: CustomPaths
  parent: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider
  langs:
  - csharp
  - vb
  name: CustomPaths
  nameWithType: ConfigFile.ClientConfigurationProvider.CustomPaths
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nList of alternate paths for GUI .config files\n"
  syntax:
    content: public static List<string> CustomPaths { get; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Shared ReadOnly Property CustomPaths As List(Of String)
  overload: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
  isExternal: true
  name: FilePath
  nameWithType: ConfigFile.ClientConfigurationProvider.FilePath
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.FilePath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
  isExternal: true
  name: CacheConfigurations
  nameWithType: ConfigFile.ClientConfigurationProvider.CacheConfigurations
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheConfigurations
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  isExternal: true
  name: CacheUserPreferences
  nameWithType: ConfigFile.ClientConfigurationProvider.CacheUserPreferences
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CacheUserPreferences
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  isExternal: true
  name: ValidateConfigurations
  nameWithType: ConfigFile.ClientConfigurationProvider.ValidateConfigurations
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.ValidateConfigurations
- uid: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
  isExternal: true
  name: CustomPaths
  nameWithType: ConfigFile.ClientConfigurationProvider.CustomPaths
  fullName: SuperOffice.Configuration.ConfigFile.ClientConfigurationProvider.CustomPaths
- uid: System.Collections.Generic.List{System.String}
  commentId: '!:System.Collections.Generic.List{System.String}'
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: System.Collections.Generic.List<>
  nameWithType.vb: List(Of )
  fullName.vb: System.Collections.Generic.List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
