### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Infrastructure
  commentId: T:SuperOffice.Configuration.ConfigFile.Infrastructure
  id: ConfigFile.Infrastructure
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
  - SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
  langs:
  - csharp
  - vb
  name: ConfigFile.Infrastructure
  nameWithType: ConfigFile.Infrastructure
  fullName: SuperOffice.Configuration.ConfigFile.Infrastructure
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values for the Online Infrastructure\n"
  syntax:
    content: 'public static class Infrastructure : Object'
    content.vb: >-
      Public Module Infrastructure

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
  commentId: P:SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
  id: CustomerStateUrl
  parent: SuperOffice.Configuration.ConfigFile.Infrastructure
  langs:
  - csharp
  - vb
  name: CustomerStateUrl
  nameWithType: ConfigFile.Infrastructure.CustomerStateUrl
  fullName: SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nUrl for looking up the customer state.\n"
  syntax:
    content: public static string CustomerStateUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CustomerStateUrl As String
  overload: SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
  commentId: P:SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
  id: IsDebugModeActivated
  parent: SuperOffice.Configuration.ConfigFile.Infrastructure
  langs:
  - csharp
  - vb
  name: IsDebugModeActivated
  nameWithType: ConfigFile.Infrastructure.IsDebugModeActivated
  fullName: SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nIs online debug mode activated\n"
  syntax:
    content: public static bool IsDebugModeActivated { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property IsDebugModeActivated As Boolean
  overload: SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
  isExternal: true
  name: CustomerStateUrl
  nameWithType: ConfigFile.Infrastructure.CustomerStateUrl
  fullName: SuperOffice.Configuration.ConfigFile.Infrastructure.CustomerStateUrl
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
  isExternal: true
  name: IsDebugModeActivated
  nameWithType: ConfigFile.Infrastructure.IsDebugModeActivated
  fullName: SuperOffice.Configuration.ConfigFile.Infrastructure.IsDebugModeActivated
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
