### YamlMime:ManagedReference
items:
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label
  commentId: T:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label
  id: ConfigurationAttributes.ControlElements.Config.Label
  parent: SuperOffice.DCF.Configuration
  children:
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TextAlign
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TrailingColon
  langs:
  - csharp
  - vb
  name: ConfigurationAttributes.ControlElements.Config.Label
  nameWithType: ConfigurationAttributes.ControlElements.Config.Label
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class Label : Object'
    content.vb: >-
      Public Module Label

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TrailingColon
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TrailingColon
  id: TrailingColon
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label
  langs:
  - csharp
  - vb
  name: TrailingColon
  nameWithType: ConfigurationAttributes.ControlElements.Config.Label.TrailingColon
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TrailingColon
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string TrailingColon = "TrailingColon"
    return:
      type: System.String
    content.vb: Public Const TrailingColon As String = "TrailingColon"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TextAlign
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TextAlign
  id: TextAlign
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label
  langs:
  - csharp
  - vb
  name: TextAlign
  nameWithType: ConfigurationAttributes.ControlElements.Config.Label.TextAlign
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.Label.TextAlign
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string TextAlign = "text-align"
    return:
      type: System.String
    content.vb: Public Const TextAlign As String = "text-align"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.DCF.Configuration
  commentId: N:SuperOffice.DCF.Configuration
  isExternal: true
  name: SuperOffice.DCF.Configuration
  nameWithType: SuperOffice.DCF.Configuration
  fullName: SuperOffice.DCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
