### YamlMime:ManagedReference
items:
- uid: SuperOffice.UI.Configuration.Constants.Clients
  commentId: T:SuperOffice.UI.Configuration.Constants.Clients
  id: Constants.Clients
  parent: SuperOffice.UI.Configuration
  children:
  - SuperOffice.UI.Configuration.Constants.Clients.None
  - SuperOffice.UI.Configuration.Constants.Clients.PocketCRM
  - SuperOffice.UI.Configuration.Constants.Clients.SixWeb
  - SuperOffice.UI.Configuration.Constants.Clients.SixWin
  langs:
  - csharp
  - vb
  name: Constants.Clients
  nameWithType: Constants.Clients
  fullName: SuperOffice.UI.Configuration.Constants.Clients
  type: Class
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nString constants for predefined client names, used when requesting a GUI from a document plugin\n"
  syntax:
    content: 'public static class Clients : Object'
    content.vb: >-
      Public Module Clients

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.UI.Configuration.Constants.Clients.SixWeb
  commentId: F:SuperOffice.UI.Configuration.Constants.Clients.SixWeb
  id: SixWeb
  parent: SuperOffice.UI.Configuration.Constants.Clients
  langs:
  - csharp
  - vb
  name: SixWeb
  nameWithType: Constants.Clients.SixWeb
  fullName: SuperOffice.UI.Configuration.Constants.Clients.SixWeb
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe 6.web (full size) client\n"
  syntax:
    content: public const string SixWeb = "6.Web"
    return:
      type: System.String
    content.vb: Public Const SixWeb As String = "6.Web"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.UI.Configuration.Constants.Clients.SixWin
  commentId: F:SuperOffice.UI.Configuration.Constants.Clients.SixWin
  id: SixWin
  parent: SuperOffice.UI.Configuration.Constants.Clients
  langs:
  - csharp
  - vb
  name: SixWin
  nameWithType: Constants.Clients.SixWin
  fullName: SuperOffice.UI.Configuration.Constants.Clients.SixWin
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe 6.win (full size) client\n"
  syntax:
    content: public const string SixWin = "6.Win"
    return:
      type: System.String
    content.vb: Public Const SixWin As String = "6.Win"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.UI.Configuration.Constants.Clients.PocketCRM
  commentId: F:SuperOffice.UI.Configuration.Constants.Clients.PocketCRM
  id: PocketCRM
  parent: SuperOffice.UI.Configuration.Constants.Clients
  langs:
  - csharp
  - vb
  name: PocketCRM
  nameWithType: Constants.Clients.PocketCRM
  fullName: SuperOffice.UI.Configuration.Constants.Clients.PocketCRM
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe PocketCRM client, running on a phone or handheld device\n"
  syntax:
    content: public const string PocketCRM = "PocketCRM"
    return:
      type: System.String
    content.vb: Public Const PocketCRM As String = "PocketCRM"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.UI.Configuration.Constants.Clients.None
  commentId: F:SuperOffice.UI.Configuration.Constants.Clients.None
  id: None
  parent: SuperOffice.UI.Configuration.Constants.Clients
  langs:
  - csharp
  - vb
  name: None
  nameWithType: Constants.Clients.None
  fullName: SuperOffice.UI.Configuration.Constants.Clients.None
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nA client that has no user interface at all; declared custom GUIs will not be instantiated in any form.\n"
  syntax:
    content: public const string None = "None"
    return:
      type: System.String
    content.vb: Public Const None As String = "None"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.UI.Configuration
  commentId: N:SuperOffice.UI.Configuration
  isExternal: true
  name: SuperOffice.UI.Configuration
  nameWithType: SuperOffice.UI.Configuration
  fullName: SuperOffice.UI.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
