### YamlMime:ManagedReference
items:
- uid: SuperOffice.UI.Configuration.Control
  commentId: T:SuperOffice.UI.Configuration.Control
  id: Control
  parent: SuperOffice.UI.Configuration
  children:
  - SuperOffice.UI.Configuration.Control.#ctor
  - SuperOffice.UI.Configuration.Control.DataSource
  - SuperOffice.UI.Configuration.Control.ID
  langs:
  - csharp
  - vb
  name: Control
  nameWithType: Control
  fullName: SuperOffice.UI.Configuration.Control
  type: Class
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\n<strong>Warning: Preliminary, informal code; subject to change!</strong><p></p>This is the base class of display controls, and defines common properties\n"
  syntax:
    content: 'public abstract class Control : Object'
    content.vb: >-
      Public MustInherit Class Control

          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - SuperOffice.UI.Configuration.Control.EnumUtil.MapEnums``2
  - SuperOffice.UI.Configuration.Control.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: SuperOffice.UI.Configuration.Control.ID
  commentId: F:SuperOffice.UI.Configuration.Control.ID
  id: ID
  parent: SuperOffice.UI.Configuration.Control
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: Control.ID
  fullName: SuperOffice.UI.Configuration.Control.ID
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe globally unique ID that identifies this control in the GUI\n"
  syntax:
    content: public string ID
    return:
      type: System.String
    content.vb: Public ID As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.UI.Configuration.Control.DataSource
  commentId: F:SuperOffice.UI.Configuration.Control.DataSource
  id: DataSource
  parent: SuperOffice.UI.Configuration.Control
  langs:
  - csharp
  - vb
  name: DataSource
  nameWithType: Control.DataSource
  fullName: SuperOffice.UI.Configuration.Control.DataSource
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  summary: "\nThe name of the data field to which this control is bound. This will typically be of the form\n&apos;Document.ExtraFields.Myfield&apos;, where MyField is the name used as key in the IDocumentInfo.ExtraFields dictionary\nthat is passed into and out of the document plugin. The name should have the form PluginName:FieldName to ensure\nuniqueness across plugins.\n"
  syntax:
    content: public string DataSource
    return:
      type: System.String
    content.vb: Public DataSource As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.UI.Configuration.Control.#ctor
  commentId: M:SuperOffice.UI.Configuration.Control.#ctor
  id: '#ctor'
  parent: SuperOffice.UI.Configuration.Control
  langs:
  - csharp
  - vb
  name: Control()
  nameWithType: Control.Control()
  fullName: SuperOffice.UI.Configuration.Control.Control()
  type: Constructor
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.UI.Configuration
  syntax:
    content: protected Control()
    content.vb: Protected Sub New
  overload: SuperOffice.UI.Configuration.Control.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: SuperOffice.UI.Configuration
  commentId: N:SuperOffice.UI.Configuration
  isExternal: true
  name: SuperOffice.UI.Configuration
  nameWithType: SuperOffice.UI.Configuration
  fullName: SuperOffice.UI.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: SuperOffice.UI.Configuration.Control.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  name: MapEnums<Control, To>()
  nameWithType: EnumUtil.MapEnums<Control, To>()
  fullName: EnumUtil.MapEnums<SuperOffice.UI.Configuration.Control, To>()
  nameWithType.vb: EnumUtil.MapEnums(Of Control, To)()
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.UI.Configuration.Control, To)()
  name.vb: MapEnums(Of Control, To)()
  spec.csharp:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums<Control, To>
    nameWithType: EnumUtil.MapEnums<Control, To>
    fullName: EnumUtil.MapEnums<SuperOffice.UI.Configuration.Control, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2
    name: MapEnums(Of Control, To)
    nameWithType: EnumUtil.MapEnums(Of Control, To)
    fullName: EnumUtil.MapEnums(Of SuperOffice.UI.Configuration.Control, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.UI.Configuration.Control.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  name: MapEnums<Control, To>()
  nameWithType: Converters.MapEnums<Control, To>()
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.UI.Configuration.Control, To>()
  nameWithType.vb: Converters.MapEnums(Of Control, To)()
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.UI.Configuration.Control, To)()
  name.vb: MapEnums(Of Control, To)()
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums<Control, To>
    nameWithType: Converters.MapEnums<Control, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.UI.Configuration.Control, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
    name: MapEnums(Of Control, To)
    nameWithType: Converters.MapEnums(Of Control, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.UI.Configuration.Control, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: EnumUtil.MapEnums<From, To>
    fullName: EnumUtil.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: EnumUtil.MapEnums(Of From, To)
    fullName: EnumUtil.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums<From, To>
    nameWithType: Converters.MapEnums<From, To>
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums(Of From, To)
    nameWithType: Converters.MapEnums(Of From, To)
    fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: From
    nameWithType: From
    fullName: From
  - name: )
    nameWithType: )
    fullName: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.UI.Configuration.Control.#ctor*
  commentId: Overload:SuperOffice.UI.Configuration.Control.#ctor
  isExternal: true
  name: Control
  nameWithType: Control.Control
  fullName: SuperOffice.UI.Configuration.Control.Control
