### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.Reporter
  commentId: T:SuperOffice.Configuration.ConfigFile.Reporter
  id: ConfigFile.Reporter
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.Reporter.ExePath
  - SuperOffice.Configuration.ConfigFile.Reporter.ODBC
  - SuperOffice.Configuration.ConfigFile.Reporter.Timeout
  langs:
  - csharp
  - vb
  name: ConfigFile.Reporter
  nameWithType: ConfigFile.Reporter
  fullName: SuperOffice.Configuration.ConfigFile.Reporter
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values related to Reporter.\n"
  syntax:
    content: 'public static class Reporter : Object'
    content.vb: >-
      Public Module Reporter

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.Reporter.ExePath
  commentId: P:SuperOffice.Configuration.ConfigFile.Reporter.ExePath
  id: ExePath
  parent: SuperOffice.Configuration.ConfigFile.Reporter
  langs:
  - csharp
  - vb
  name: ExePath
  nameWithType: ConfigFile.Reporter.ExePath
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.ExePath
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nContains the path to the folder where the file SoReporterExecuter.exe is located.\n"
  syntax:
    content: public static string ExePath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ExePath As String
  overload: SuperOffice.Configuration.ConfigFile.Reporter.ExePath*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Reporter.Timeout
  commentId: P:SuperOffice.Configuration.ConfigFile.Reporter.Timeout
  id: Timeout
  parent: SuperOffice.Configuration.ConfigFile.Reporter
  langs:
  - csharp
  - vb
  name: Timeout
  nameWithType: ConfigFile.Reporter.Timeout
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.Timeout
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nTimeout in milliseconds for the reporter process.\n"
  syntax:
    content: public static int Timeout { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property Timeout As Integer
  overload: SuperOffice.Configuration.ConfigFile.Reporter.Timeout*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.Reporter.ODBC
  commentId: P:SuperOffice.Configuration.ConfigFile.Reporter.ODBC
  id: ODBC
  parent: SuperOffice.Configuration.ConfigFile.Reporter
  langs:
  - csharp
  - vb
  name: ODBC
  nameWithType: ConfigFile.Reporter.ODBC
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.ODBC
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nODBC Datasource name to use when running Reporter\n"
  syntax:
    content: public static string ODBC { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property ODBC As String
  overload: SuperOffice.Configuration.ConfigFile.Reporter.ODBC*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.Reporter.ExePath*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Reporter.ExePath
  isExternal: true
  name: ExePath
  nameWithType: ConfigFile.Reporter.ExePath
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.ExePath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.Reporter.Timeout*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Reporter.Timeout
  isExternal: true
  name: Timeout
  nameWithType: ConfigFile.Reporter.Timeout
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.Timeout
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SuperOffice.Configuration.ConfigFile.Reporter.ODBC*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.Reporter.ODBC
  isExternal: true
  name: ODBC
  nameWithType: ConfigFile.Reporter.ODBC
  fullName: SuperOffice.Configuration.ConfigFile.Reporter.ODBC
