### YamlMime:ManagedReference
items:
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  commentId: T:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  id: ConfigurationAttributes.ControlElements.Config.TextField
  parent: SuperOffice.DCF.Configuration
  children:
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Alphanumeric
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Center
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Float
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Integer
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Left
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Mask
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.MaxLength
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Money
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Right
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Rows
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.TextAlign
  - SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Type
  langs:
  - csharp
  - vb
  name: ConfigurationAttributes.ControlElements.Config.TextField
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: 'public static class TextField : Object'
    content.vb: >-
      Public Module TextField

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Type
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Type
  id: Type
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Type
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Type
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Type = "type"
    return:
      type: System.String
    content.vb: Public Const Type As String = "type"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Mask
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Mask
  id: Mask
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Mask
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Mask
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Mask
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Mask = "mask"
    return:
      type: System.String
    content.vb: Public Const Mask As String = "mask"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.MaxLength
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.MaxLength
  id: MaxLength
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: MaxLength
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.MaxLength
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.MaxLength
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string MaxLength = "max-length"
    return:
      type: System.String
    content.vb: Public Const MaxLength As String = "max-length"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Rows
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Rows
  id: Rows
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Rows
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Rows
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Rows
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Rows = "rows"
    return:
      type: System.String
    content.vb: Public Const Rows As String = "rows"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.TextAlign
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.TextAlign
  id: TextAlign
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: TextAlign
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.TextAlign
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.TextAlign
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string TextAlign = "text-align"
    return:
      type: System.String
    content.vb: Public Const TextAlign As String = "text-align"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Left
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Left
  id: Left
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Left
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Left
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Left
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Left = "left"
    return:
      type: System.String
    content.vb: Public Const Left As String = "left"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Right
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Right
  id: Right
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Right
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Right
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Right
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Right = "right"
    return:
      type: System.String
    content.vb: Public Const Right As String = "right"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Center
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Center
  id: Center
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Center
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Center
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Center
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Center = "center"
    return:
      type: System.String
    content.vb: Public Const Center As String = "center"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Alphanumeric
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Alphanumeric
  id: Alphanumeric
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Alphanumeric
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Alphanumeric
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Alphanumeric
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Alphanumeric = "alphanumeric"
    return:
      type: System.String
    content.vb: Public Const Alphanumeric As String = "alphanumeric"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Integer
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Integer
  id: Integer
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Integer
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Integer
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Integer
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Integer = "integer"
    return:
      type: System.String
    content.vb: Public Const Integer As String = "integer"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Float
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Float
  id: Float
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Float
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Float
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Float
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Float = "float"
    return:
      type: System.String
    content.vb: Public Const Float As String = "float"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Money
  commentId: F:SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Money
  id: Money
  parent: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField
  langs:
  - csharp
  - vb
  name: Money
  nameWithType: ConfigurationAttributes.ControlElements.Config.TextField.Money
  fullName: SuperOffice.DCF.Configuration.ConfigurationAttributes.ControlElements.Config.TextField.Money
  type: Field
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.DCF.Configuration
  summary: "\n\n"
  syntax:
    content: public const string Money = "money"
    return:
      type: System.String
    content.vb: Public Const Money As String = "money"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.DCF.Configuration
  commentId: N:SuperOffice.DCF.Configuration
  isExternal: true
  name: SuperOffice.DCF.Configuration
  nameWithType: SuperOffice.DCF.Configuration
  fullName: SuperOffice.DCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
