### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Documents.Constants.Values
  commentId: T:SuperOffice.CRM.Documents.Constants.Values
  id: Constants.Values
  parent: SuperOffice.CRM.Documents
  children:
  - SuperOffice.CRM.Documents.Constants.Values.False
  - SuperOffice.CRM.Documents.Constants.Values.Mandatory
  - SuperOffice.CRM.Documents.Constants.Values.Optional
  - SuperOffice.CRM.Documents.Constants.Values.Stream
  - SuperOffice.CRM.Documents.Constants.Values.True
  - SuperOffice.CRM.Documents.Constants.Values.Url
  langs:
  - csharp
  - vb
  name: Constants.Values
  nameWithType: Constants.Values
  fullName: SuperOffice.CRM.Documents.Constants.Values
  type: Class
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\nString constants for capability and property values, where fixed values are used\n"
  syntax:
    content: 'public static class Values : Object'
    content.vb: >-
      Public Module Values

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.CRM.Documents.Constants.Values.True
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.True
  id: "True"
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: "True"
  nameWithType: Constants.Values.True
  fullName: SuperOffice.CRM.Documents.Constants.Values.True
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\nThe value used to indicate a true/present/supported status\n"
  syntax:
    content: public const string True = "true"
    return:
      type: System.String
    content.vb: Public Const True As String = "true"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Documents.Constants.Values.False
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.False
  id: "False"
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: "False"
  nameWithType: Constants.Values.False
  fullName: SuperOffice.CRM.Documents.Constants.Values.False
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\nThe value used to indicate a false/missing/not supported status\n"
  syntax:
    content: public const string False = "false"
    return:
      type: System.String
    content.vb: Public Const False As String = "false"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Documents.Constants.Values.Optional
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.Optional
  id: Optional
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: Optional
  nameWithType: Constants.Values.Optional
  fullName: SuperOffice.CRM.Documents.Constants.Values.Optional
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\nThe value used to indicate an optional status\n"
  syntax:
    content: public const string Optional = "optional"
    return:
      type: System.String
    content.vb: Public Const Optional As String = "optional"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Documents.Constants.Values.Mandatory
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.Mandatory
  id: Mandatory
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: Mandatory
  nameWithType: Constants.Values.Mandatory
  fullName: SuperOffice.CRM.Documents.Constants.Values.Mandatory
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\nThe value used to indicate a mandatory status\n"
  syntax:
    content: public const string Mandatory = "mandatory"
    return:
      type: System.String
    content.vb: Public Const Mandatory As String = "mandatory"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Documents.Constants.Values.Url
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.Url
  id: Url
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: Url
  nameWithType: Constants.Values.Url
  fullName: SuperOffice.CRM.Documents.Constants.Values.Url
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\n&apos;url&apos;, the value of the <xref href=\"SuperOffice.CRM.Documents.Constants.Properties.PreferredOpen\" data-throw-if-not-resolved=\"false\"></xref> property that specifies that URL (WebDAV) is the preferred\naccess method to this document.\n"
  syntax:
    content: public const string Url = "url"
    return:
      type: System.String
    content.vb: Public Const Url As String = "url"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Documents.Constants.Values.Stream
  commentId: F:SuperOffice.CRM.Documents.Constants.Values.Stream
  id: Stream
  parent: SuperOffice.CRM.Documents.Constants.Values
  langs:
  - csharp
  - vb
  name: Stream
  nameWithType: Constants.Values.Stream
  fullName: SuperOffice.CRM.Documents.Constants.Values.Stream
  type: Field
  source:
    path: SuperOffice.Plugins
    isExternal: true
  assemblies:
  - SuperOffice.Plugins
  namespace: SuperOffice.CRM.Documents
  summary: "\n&apos;stream&apos;, the value of the <xref href=\"SuperOffice.CRM.Documents.Constants.Properties.PreferredOpen\" data-throw-if-not-resolved=\"false\"></xref> property that specifies that stream\naccess is preferred for this document. Note that stream access must always be supported,\neven if <xref href=\"SuperOffice.CRM.Documents.Constants.Properties.PreferredOpen\" data-throw-if-not-resolved=\"false\"></xref> is returned.\n"
  syntax:
    content: public const string Stream = "stream"
    return:
      type: System.String
    content.vb: Public Const Stream As String = "stream"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.CRM.Documents
  commentId: N:SuperOffice.CRM.Documents
  isExternal: true
  name: SuperOffice.CRM.Documents
  nameWithType: SuperOffice.CRM.Documents
  fullName: SuperOffice.CRM.Documents
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
