### YamlMime:ManagedReference
items:
- uid: SuperOffice.Configuration.ConfigFile.CustomerService
  commentId: T:SuperOffice.Configuration.ConfigFile.CustomerService
  id: ConfigFile.CustomerService
  parent: SuperOffice.Configuration
  children:
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
  - SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
  - SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
  - SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
  langs:
  - csharp
  - vb
  name: ConfigFile.CustomerService
  nameWithType: ConfigFile.CustomerService
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService
  type: Class
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nConfiguration values for accessing Customer Service\n"
  syntax:
    content: 'public static class CustomerService : Object'
    content.vb: >-
      Public Module CustomerService

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
  id: ImpersonateCsUser
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: ImpersonateCsUser
  nameWithType: ConfigFile.CustomerService.ImpersonateCsUser
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nImpersonate a specific (Windows Domain) user when using Customer Service API\n"
  syntax:
    content: public static bool ImpersonateCsUser { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property ImpersonateCsUser As Boolean
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
  id: CsUserName
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsUserName
  nameWithType: ConfigFile.CustomerService.CsUserName
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe username to impersonate\n"
  syntax:
    content: public static string CsUserName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsUserName As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
  id: CsPassword
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsPassword
  nameWithType: ConfigFile.CustomerService.CsPassword
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe password\n"
  syntax:
    content: public static string CsPassword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsPassword As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
  id: CsDomain
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsDomain
  nameWithType: ConfigFile.CustomerService.CsDomain
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nThe Active Directory Domain this user belongs to\n"
  syntax:
    content: public static string CsDomain { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsDomain As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
  id: CsCgiUrl
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsCgiUrl
  nameWithType: ConfigFile.CustomerService.CsCgiUrl
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nBase path for CustomerService as accessed from browser when accessed from internet and public urls.  Like customer center or links in mailings (Online only)\n"
  syntax:
    content: public static string CsCgiUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsCgiUrl As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
  id: CsCgiUrlInternal
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsCgiUrlInternal
  nameWithType: ConfigFile.CustomerService.CsCgiUrlInternal
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nBase path for CustomerService as used by an internal employee working with service (Front-channel from associate) (Online only)\n"
  syntax:
    content: public static string CsCgiUrlInternal { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsCgiUrlInternal As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
  id: CsCgiUrlDirect
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: CsCgiUrlDirect
  nameWithType: ConfigFile.CustomerService.CsCgiUrlDirect
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nBase path for CustomerService as accessed from NetServer (Back-channel) (Online only)\n"
  syntax:
    content: public static string CsCgiUrlDirect { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property CsCgiUrlDirect As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
  commentId: P:SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
  id: MailDomain
  parent: SuperOffice.Configuration.ConfigFile.CustomerService
  langs:
  - csharp
  - vb
  name: MailDomain
  nameWithType: ConfigFile.CustomerService.MailDomain
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
  type: Property
  source:
    path: SoCore
    isExternal: true
  assemblies:
  - SoCore
  namespace: SuperOffice.Configuration
  summary: "\nMail domain used in Customer Service\n"
  syntax:
    content: public static string MailDomain { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property MailDomain As String
  overload: SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: SuperOffice.Configuration
  commentId: N:SuperOffice.Configuration
  isExternal: true
  name: SuperOffice.Configuration
  nameWithType: SuperOffice.Configuration
  fullName: SuperOffice.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
  isExternal: true
  name: ImpersonateCsUser
  nameWithType: ConfigFile.CustomerService.ImpersonateCsUser
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.ImpersonateCsUser
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
  isExternal: true
  name: CsUserName
  nameWithType: ConfigFile.CustomerService.CsUserName
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsUserName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
  isExternal: true
  name: CsPassword
  nameWithType: ConfigFile.CustomerService.CsPassword
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsPassword
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
  isExternal: true
  name: CsDomain
  nameWithType: ConfigFile.CustomerService.CsDomain
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsDomain
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
  isExternal: true
  name: CsCgiUrl
  nameWithType: ConfigFile.CustomerService.CsCgiUrl
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrl
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
  isExternal: true
  name: CsCgiUrlInternal
  nameWithType: ConfigFile.CustomerService.CsCgiUrlInternal
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlInternal
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
  isExternal: true
  name: CsCgiUrlDirect
  nameWithType: ConfigFile.CustomerService.CsCgiUrlDirect
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.CsCgiUrlDirect
- uid: SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain*
  commentId: Overload:SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
  isExternal: true
  name: MailDomain
  nameWithType: ConfigFile.CustomerService.MailDomain
  fullName: SuperOffice.Configuration.ConfigFile.CustomerService.MailDomain
