### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields
  commentId: T:SuperOffice.CRM.Data.DBC.CustConfigFields
  id: DBC.CustConfigFields
  parent: SuperOffice.CRM.Data
  children:
  - SuperOffice.CRM.Data.DBC.CustConfigFields.Config
  - SuperOffice.CRM.Data.DBC.CustConfigFields.CustConfigId
  - SuperOffice.CRM.Data.DBC.CustConfigFields.CustLangId
  - SuperOffice.CRM.Data.DBC.CustConfigFields.Registered
  - SuperOffice.CRM.Data.DBC.CustConfigFields.RegisteredAssociateId
  - SuperOffice.CRM.Data.DBC.CustConfigFields.Type
  - SuperOffice.CRM.Data.DBC.CustConfigFields.Updated
  - SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedAssociateId
  - SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedCount
  langs:
  - csharp
  - vb
  name: DBC.CustConfigFields
  nameWithType: DBC.CustConfigFields
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields
  type: Class
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nFields for CustConfig, This table contains JSON structures used for customizing the customer center\n"
  syntax:
    content: 'public static class CustConfigFields : Object'
    content.vb: >-
      Public Module CustConfigFields

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.CustConfigId
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.CustConfigId
  id: CustConfigId
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: CustConfigId
  nameWithType: DBC.CustConfigFields.CustConfigId
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.CustConfigId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.CustConfigId: Primary key\n"
  syntax:
    content: public const string CustConfigId = "cust_config_id"
    return:
      type: System.String
    content.vb: Public Const CustConfigId As String = "cust_config_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.Type
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.Type
  id: Type
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: DBC.CustConfigFields.Type
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.Type
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.Type: What kind of data is in this row\n"
  syntax:
    content: public const string Type = "type"
    return:
      type: System.String
    content.vb: Public Const Type As String = "type"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.Config
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.Config
  id: Config
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: DBC.CustConfigFields.Config
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.Config
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.Config: A JSON-formatted config\n"
  syntax:
    content: public const string Config = "config"
    return:
      type: System.String
    content.vb: Public Const Config As String = "config"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.CustLangId
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.CustLangId
  id: CustLangId
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: CustLangId
  nameWithType: DBC.CustConfigFields.CustLangId
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.CustLangId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.CustLangId: The customer language which this config belongs to. 0 indicates that the config is global\n"
  syntax:
    content: public const string CustLangId = "cust_lang_id"
    return:
      type: System.String
    content.vb: Public Const CustLangId As String = "cust_lang_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.Registered
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.Registered
  id: Registered
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: Registered
  nameWithType: DBC.CustConfigFields.Registered
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.Registered
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.Registered: Registered when\n"
  syntax:
    content: public const string Registered = "registered"
    return:
      type: System.String
    content.vb: Public Const Registered As String = "registered"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.RegisteredAssociateId
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.RegisteredAssociateId
  id: RegisteredAssociateId
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: RegisteredAssociateId
  nameWithType: DBC.CustConfigFields.RegisteredAssociateId
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.RegisteredAssociateId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.RegisteredAssociateId: Registered by whom\n"
  syntax:
    content: public const string RegisteredAssociateId = "registered_associate_id"
    return:
      type: System.String
    content.vb: Public Const RegisteredAssociateId As String = "registered_associate_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.Updated
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.Updated
  id: Updated
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: Updated
  nameWithType: DBC.CustConfigFields.Updated
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.Updated
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.Updated: Last updated when\n"
  syntax:
    content: public const string Updated = "updated"
    return:
      type: System.String
    content.vb: Public Const Updated As String = "updated"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedAssociateId
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedAssociateId
  id: UpdatedAssociateId
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: UpdatedAssociateId
  nameWithType: DBC.CustConfigFields.UpdatedAssociateId
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedAssociateId
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.UpdatedAssociateId: Last updated by whom\n"
  syntax:
    content: public const string UpdatedAssociateId = "updated_associate_id"
    return:
      type: System.String
    content.vb: Public Const UpdatedAssociateId As String = "updated_associate_id"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedCount
  commentId: F:SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedCount
  id: UpdatedCount
  parent: SuperOffice.CRM.Data.DBC.CustConfigFields
  langs:
  - csharp
  - vb
  name: UpdatedCount
  nameWithType: DBC.CustConfigFields.UpdatedCount
  fullName: SuperOffice.CRM.Data.DBC.CustConfigFields.UpdatedCount
  type: Field
  source:
    path: SoDataBase
    isExternal: true
  assemblies:
  - SoDataBase
  namespace: SuperOffice.CRM.Data
  summary: "\nCustConfig.UpdatedCount: Number of updates made to this record\n"
  syntax:
    content: public const string UpdatedCount = "updatedCount"
    return:
      type: System.String
    content.vb: Public Const UpdatedCount As String = "updatedCount"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: SuperOffice.CRM.Data
  commentId: N:SuperOffice.CRM.Data
  isExternal: true
  name: SuperOffice.CRM.Data
  nameWithType: SuperOffice.CRM.Data
  fullName: SuperOffice.CRM.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
