### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Services.CustomerServiceConfig
  commentId: T:SuperOffice.CRM.Services.CustomerServiceConfig
  id: CustomerServiceConfig
  parent: SuperOffice.CRM.Services
  children:
  - SuperOffice.CRM.Services.CustomerServiceConfig.#ctor
  - SuperOffice.CRM.Services.CustomerServiceConfig.ToString
  - SuperOffice.CRM.Services.CustomerServiceConfig.ToString(System.String)
  langs:
  - csharp
  - vb
  name: CustomerServiceConfig
  nameWithType: CustomerServiceConfig
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig
  type: Class
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: >-
    This contains different configuration methods regarding Service

    <p></p>

    Carrier object for CustomerServiceConfig.

    Services for the CustomerServiceConfig Carrier is available from the <xref href="SuperOffice.CRM.Services.ICustomerServiceAgent?text=CustomerService+Agent" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: >-
      [DataContract(Namespace = "http://www.superoffice.net/ws/crm/NetServer/11.8.0.0")]

      public class CustomerServiceConfig : Carrier
    content.vb: >-
      <DataContract(Namespace:="http://www.superoffice.net/ws/crm/NetServer/11.8.0.0")>

      Public Class CustomerServiceConfig Inherits Carrier
  seealso:
  - linkId: SuperOffice.CRM.Services.ICustomerServiceAgent
    commentId: T:SuperOffice.CRM.Services.ICustomerServiceAgent
  inheritance:
  - System.Object
  attributes:
  - type: System.Runtime.Serialization.DataContractAttribute
    ctor: System.Runtime.Serialization.DataContractAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Namespace
      type: System.String
      value: http://www.superoffice.net/ws/crm/NetServer/11.8.0.0
- uid: SuperOffice.CRM.Services.CustomerServiceConfig.#ctor
  commentId: M:SuperOffice.CRM.Services.CustomerServiceConfig.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Services.CustomerServiceConfig
  langs:
  - csharp
  - vb
  name: CustomerServiceConfig()
  nameWithType: CustomerServiceConfig.CustomerServiceConfig()
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig.CustomerServiceConfig()
  type: Constructor
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: Default constructor
  example: []
  syntax:
    content: public CustomerServiceConfig()
    content.vb: Public Sub New()
  overload: SuperOffice.CRM.Services.CustomerServiceConfig.#ctor*
  nameWithType.vb: CustomerServiceConfig.New()
  fullName.vb: SuperOffice.CRM.Services.CustomerServiceConfig.New()
  name.vb: New()
- uid: SuperOffice.CRM.Services.CustomerServiceConfig.ToString
  commentId: M:SuperOffice.CRM.Services.CustomerServiceConfig.ToString
  id: ToString
  parent: SuperOffice.CRM.Services.CustomerServiceConfig
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: CustomerServiceConfig.ToString()
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig.ToString()
  type: Method
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: Returns the carrier contents as a formatted string.
  example: []
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Overrides Function ToString() As String
  overload: SuperOffice.CRM.Services.CustomerServiceConfig.ToString*
- uid: SuperOffice.CRM.Services.CustomerServiceConfig.ToString(System.String)
  commentId: M:SuperOffice.CRM.Services.CustomerServiceConfig.ToString(System.String)
  id: ToString(System.String)
  parent: SuperOffice.CRM.Services.CustomerServiceConfig
  langs:
  - csharp
  - vb
  name: ToString(string)
  nameWithType: CustomerServiceConfig.ToString(string)
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig.ToString(string)
  type: Method
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: >-
    Returns the carrier contents as a formatted string, useful for debugging.

    Each line in the output is prefixed with the input value.
  example: []
  syntax:
    content: public string ToString(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: The line prefix (typically used for indenting)
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Function ToString(prefix As String) As String
  overload: SuperOffice.CRM.Services.CustomerServiceConfig.ToString*
  nameWithType.vb: CustomerServiceConfig.ToString(String)
  fullName.vb: SuperOffice.CRM.Services.CustomerServiceConfig.ToString(String)
  name.vb: ToString(String)
references:
- uid: SuperOffice.CRM.Services.ICustomerServiceAgent
  commentId: T:SuperOffice.CRM.Services.ICustomerServiceAgent
  parent: SuperOffice.CRM.Services
  isExternal: true
  href: SuperOffice.CRM.Services.ICustomerServiceAgent.html
  name: ICustomerServiceAgent
  nameWithType: ICustomerServiceAgent
  fullName: SuperOffice.CRM.Services.ICustomerServiceAgent
- uid: SuperOffice.CRM.Services
  commentId: N:SuperOffice.CRM.Services
  isExternal: true
  href: SuperOffice.html
  name: SuperOffice.CRM.Services
  nameWithType: SuperOffice.CRM.Services
  fullName: SuperOffice.CRM.Services
  spec.csharp:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.CRM
    name: CRM
    isExternal: true
    href: SuperOffice.CRM.html
  - name: .
  - uid: SuperOffice.CRM.Services
    name: Services
    isExternal: true
    href: SuperOffice.CRM.Services.html
  spec.vb:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.CRM
    name: CRM
    isExternal: true
    href: SuperOffice.CRM.html
  - name: .
  - uid: SuperOffice.CRM.Services
    name: Services
    isExternal: true
    href: SuperOffice.CRM.Services.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.CRM.Services.CustomerServiceConfig.#ctor*
  commentId: Overload:SuperOffice.CRM.Services.CustomerServiceConfig.#ctor
  isExternal: true
  href: SuperOffice.CRM.Services.CustomerServiceConfig.html#SuperOffice_CRM_Services_CustomerServiceConfig__ctor
  name: CustomerServiceConfig
  nameWithType: CustomerServiceConfig.CustomerServiceConfig
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig.CustomerServiceConfig
  nameWithType.vb: CustomerServiceConfig.New
  fullName.vb: SuperOffice.CRM.Services.CustomerServiceConfig.New
  name.vb: New
- uid: SuperOffice.CRM.Services.CustomerServiceConfig.ToString*
  commentId: Overload:SuperOffice.CRM.Services.CustomerServiceConfig.ToString
  isExternal: true
  href: SuperOffice.CRM.Services.CustomerServiceConfig.html#SuperOffice_CRM_Services_CustomerServiceConfig_ToString
  name: ToString
  nameWithType: CustomerServiceConfig.ToString
  fullName: SuperOffice.CRM.Services.CustomerServiceConfig.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
