### YamlMime:ManagedReference
items:
- uid: SuperOffice.CRM.Services.LiveUiConfig
  commentId: T:SuperOffice.CRM.Services.LiveUiConfig
  id: LiveUiConfig
  parent: SuperOffice.CRM.Services
  children:
  - SuperOffice.CRM.Services.LiveUiConfig.#ctor
  - SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
  - SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
  - SuperOffice.CRM.Services.LiveUiConfig.ToString
  - SuperOffice.CRM.Services.LiveUiConfig.ToString(System.String)
  langs:
  - csharp
  - vb
  name: LiveUiConfig
  nameWithType: LiveUiConfig
  fullName: SuperOffice.CRM.Services.LiveUiConfig
  type: Class
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nA config containing parameters for live UI\n<p></p>\nCarrier object for LiveUiConfig.\nServices for the LiveUiConfig Carrier is available from the <xref href=\"SuperOffice.CRM.Services.IViewStateAgent\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  syntax:
    content: 'public class LiveUiConfig : Carrier'
    content.vb: >-
      Public Class LiveUiConfig

          Inherits Carrier
  seealso:
  - linkId: SuperOffice.CRM.Services.ViewStateAgent
    commentId: T:SuperOffice.CRM.Services.ViewStateAgent
  - linkId: SuperOffice.CRM.Services.IViewStateAgent
    commentId: T:SuperOffice.CRM.Services.IViewStateAgent
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SuperOffice.CRM.Services.LiveUiConfig.#ctor
  commentId: M:SuperOffice.CRM.Services.LiveUiConfig.#ctor
  id: '#ctor'
  parent: SuperOffice.CRM.Services.LiveUiConfig
  langs:
  - csharp
  - vb
  name: LiveUiConfig()
  nameWithType: LiveUiConfig.LiveUiConfig()
  fullName: SuperOffice.CRM.Services.LiveUiConfig.LiveUiConfig()
  type: Constructor
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nDefault constructor\n"
  syntax:
    content: public LiveUiConfig()
    content.vb: Public Sub New
  overload: SuperOffice.CRM.Services.LiveUiConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.LiveUiConfig.ToString
  commentId: M:SuperOffice.CRM.Services.LiveUiConfig.ToString
  id: ToString
  parent: SuperOffice.CRM.Services.LiveUiConfig
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: LiveUiConfig.ToString()
  fullName: SuperOffice.CRM.Services.LiveUiConfig.ToString()
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string.\n"
  syntax:
    content: public override string ToString()
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Overrides Function ToString As String
  overload: SuperOffice.CRM.Services.LiveUiConfig.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: SuperOffice.CRM.Services.LiveUiConfig.ToString(System.String)
  commentId: M:SuperOffice.CRM.Services.LiveUiConfig.ToString(System.String)
  id: ToString(System.String)
  parent: SuperOffice.CRM.Services.LiveUiConfig
  langs:
  - csharp
  - vb
  name: ToString(String)
  nameWithType: LiveUiConfig.ToString(String)
  fullName: SuperOffice.CRM.Services.LiveUiConfig.ToString(System.String)
  type: Method
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nReturns the carrier contents as a formatted string, useful for debugging.\nEach line in the output is prefixed with the input value.\n"
  syntax:
    content: public string ToString(string prefix)
    parameters:
    - id: prefix
      type: System.String
      description: The line prefix (typically used for indenting)
    return:
      type: System.String
      description: The carrier contents.
    content.vb: Public Function ToString(prefix As String) As String
  overload: SuperOffice.CRM.Services.LiveUiConfig.ToString*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
  commentId: P:SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
  id: IsEnabled
  parent: SuperOffice.CRM.Services.LiveUiConfig
  langs:
  - csharp
  - vb
  name: IsEnabled
  nameWithType: LiveUiConfig.IsEnabled
  fullName: SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nIndicates whether live UI is enabled \n"
  syntax:
    content: public virtual bool IsEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Overridable Property IsEnabled As Boolean
  overload: SuperOffice.CRM.Services.LiveUiConfig.IsEnabled*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
  commentId: P:SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
  id: PollingInterval
  parent: SuperOffice.CRM.Services.LiveUiConfig
  langs:
  - csharp
  - vb
  name: PollingInterval
  nameWithType: LiveUiConfig.PollingInterval
  fullName: SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
  type: Property
  source:
    path: SuperOffice.Services
    isExternal: true
  assemblies:
  - SuperOffice.Services
  namespace: SuperOffice.CRM.Services
  summary: "\nInterval (in seconds) defining how often UI events should be polled. \n"
  syntax:
    content: public virtual int PollingInterval { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Overridable Property PollingInterval As Integer
  overload: SuperOffice.CRM.Services.LiveUiConfig.PollingInterval*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: SuperOffice.CRM.Services
  commentId: N:SuperOffice.CRM.Services
  isExternal: true
  name: SuperOffice.CRM.Services
  nameWithType: SuperOffice.CRM.Services
  fullName: SuperOffice.CRM.Services
- uid: SuperOffice.CRM.Services.ViewStateAgent
  commentId: T:SuperOffice.CRM.Services.ViewStateAgent
  isExternal: true
  name: ViewStateAgent
  nameWithType: ViewStateAgent
  fullName: SuperOffice.CRM.Services.ViewStateAgent
- uid: SuperOffice.CRM.Services.IViewStateAgent
  commentId: T:SuperOffice.CRM.Services.IViewStateAgent
  parent: SuperOffice.CRM.Services
  isExternal: true
  name: IViewStateAgent
  nameWithType: IViewStateAgent
  fullName: SuperOffice.CRM.Services.IViewStateAgent
- uid: SuperOffice.CRM.Services.LiveUiConfig.#ctor*
  commentId: Overload:SuperOffice.CRM.Services.LiveUiConfig.#ctor
  isExternal: true
  name: LiveUiConfig
  nameWithType: LiveUiConfig.LiveUiConfig
  fullName: SuperOffice.CRM.Services.LiveUiConfig.LiveUiConfig
- uid: SuperOffice.CRM.Services.LiveUiConfig.ToString*
  commentId: Overload:SuperOffice.CRM.Services.LiveUiConfig.ToString
  isExternal: true
  name: ToString
  nameWithType: LiveUiConfig.ToString
  fullName: SuperOffice.CRM.Services.LiveUiConfig.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.CRM.Services.LiveUiConfig.IsEnabled*
  commentId: Overload:SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
  isExternal: true
  name: IsEnabled
  nameWithType: LiveUiConfig.IsEnabled
  fullName: SuperOffice.CRM.Services.LiveUiConfig.IsEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SuperOffice.CRM.Services.LiveUiConfig.PollingInterval*
  commentId: Overload:SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
  isExternal: true
  name: PollingInterval
  nameWithType: LiveUiConfig.PollingInterval
  fullName: SuperOffice.CRM.Services.LiveUiConfig.PollingInterval
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
